// src/services/arena/relayService.ts
import { Groq } from 'groq-sdk';

const ACTIVE_GROQ_KEY = process.env.EXPO_PUBLIC_GROQ_API_KEY || '';
const groq = new Groq({ apiKey: ACTIVE_GROQ_KEY, dangerouslyAllowBrowser: true });

export interface RelayChallenge {
  id: string;
  topic: string;
  contextEn: string;
  contextVi?: string;
  player1En: string;
  player1Vi?: string;
  player2En: string;
  player2Vi?: string;
  keyVocabulary: string[];
}

const sessionUsedRelayTexts: Set<string> = new Set();

export function clearRelayHistory() {
  sessionUsedRelayTexts.clear();
}

// 📦 KHO DỮ LIỆU LOCAL 50 CHỦ ĐỀ RELAY ĐỘC BẢN CHO MỖI LEVEL (TỔNG 300 CHỦ ĐỀ RELAY)
const LOCAL_RELAY_POOL: Record<string, RelayChallenge[]> = {
  A1: [
    { id: 'r_a1_1', topic: "Daily Habits [A1]", contextEn: "Discuss your daily routine.", contextVi: "Thảo luận về thói quen hàng ngày.", player1En: "Talk about your morning routine.", player1Vi: "Nói về thói quen buổi sáng.", player2En: "Talk about your evening activities.", player2Vi: "Nói về các hoạt động buổi tối.", keyVocabulary: ["routine"] },
    { id: 'r_a1_2', topic: "Favorite Food [A1]", contextEn: "Talking about food preferences.", contextVi: "Nói về sở thích ăn uống.", player1En: "Talk about your favorite breakfast.", player1Vi: "Nói về bữa sáng yêu thích.", player2En: "Talk about what you like for dinner.", player2Vi: "Nói về món ăn tối yêu thích.", keyVocabulary: ["food"] },
    { id: 'r_a1_3', topic: "Weekend Activities [A1]", contextEn: "Planning weekend fun.", contextVi: "Lên kế hoạch vui chơi cuối tuần.", player1En: "Suggest Saturday activities.", player1Vi: "Gợi ý các hoạt động thứ 7.", player2En: "Suggest Sunday relaxation.", player2Vi: "Gợi ý thư giãn vào Chủ Nhật.", keyVocabulary: ["weekend"] },
    { id: 'r_a1_4', topic: "My House [A1]", contextEn: "Describing rooms in your home.", contextVi: "Mô tả các phòng trong nhà bạn.", player1En: "Describe your living room.", player1Vi: "Mô tả phòng khách.", player2En: "Describe your bedroom.", player2Vi: "Mô tả phòng ngủ.", keyVocabulary: ["house"] },
    { id: 'r_a1_5', topic: "School Life [A1]", contextEn: "Talking about favorite school subjects.", contextVi: "Nói về các môn học yêu thích.", player1En: "Talk about your favorite teacher.", player1Vi: "Nói về giáo viên bạn thích.", player2En: "Talk about your favorite subject.", player2Vi: "Nói về môn học yêu thích.", keyVocabulary: ["school"] },
    { id: 'r_a1_6', topic: "Weather Today [A1]", contextEn: "Discussing daily weather.", contextVi: "Thảo luận thời tiết hôm nay.", player1En: "Talk about sunny weather activities.", player1Vi: "Nói về hoạt động ngày nắng.", player2En: "Talk about rainy day plans.", player2Vi: "Nói về kế hoạch ngày mưa.", keyVocabulary: ["weather"] },
    { id: 'r_a1_7', topic: "Pets & Animals [A1]", contextEn: "Talking about household pets.", contextVi: "Nói về thú cưng trong nhà.", player1En: "Talk about dogs or cats.", player1Vi: "Nói về chó hoặc mèo.", player2En: "Talk about feeding pets.", player2Vi: "Nói về việc cho thú cưng ăn.", keyVocabulary: ["pet"] },
    { id: 'r_a1_8', topic: "Clothes & Style [A1]", contextEn: "Discussing daily outfit choices.", contextVi: "Thảo luận lựa chọn trang phục.", player1En: "Talk about summer clothes.", player1Vi: "Nói về quần áo mùa hè.", player2En: "Talk about winter coats.", player2Vi: "Nói về áo khoác mùa đông.", keyVocabulary: ["clothes"] },
    { id: 'r_a1_9', topic: "Family Vacation [A1]", contextEn: "Planning a family trip.", contextVi: "Lên kế hoạch du lịch gia đình.", player1En: "Suggest visiting the beach.", player1Vi: "Gợi ý đi biển.", player2En: "Suggest visiting the mountains.", player2Vi: "Gợi ý đi núi.", keyVocabulary: ["vacation"] },
    { id: 'r_a1_10', topic: "Sports & Games [A1]", contextEn: "Talking about outdoor games.", contextVi: "Nói về các trò chơi ngoài trời.", player1En: "Talk about football.", player1Vi: "Nói về bóng đá.", player2En: "Talk about badminton.", player2Vi: "Nói về cầu lông.", keyVocabulary: ["sports"] },
    { id: 'r_a1_11', topic: "At the Supermarket [A1]", contextEn: "Buying groceries for the week.", contextVi: "Mua thực phẩm cho cả tuần.", player1En: "Talk about buying fruits and vegetables.", player1Vi: "Nói về mua trái cây và rau.", player2En: "Talk about buying milk and bread.", player2Vi: "Nói về mua sữa và bánh mì.", keyVocabulary: ["groceries"] },
    { id: 'r_a1_12', topic: "Birthday Present [A1]", contextEn: "Choosing a gift for a friend.", contextVi: "Chọn quà sinh nhật cho bạn.", player1En: "Suggest buying a book.", player1Vi: "Gợi ý mua một cuốn sách.", player2En: "Suggest buying a toy or accessory.", player2Vi: "Gợi ý mua đồ chơi hoặc phụ kiện.", keyVocabulary: ["gift"] },
    { id: 'r_a1_13', topic: "My Favorite Park [A1]", contextEn: "Walking in a city park.", contextVi: "Đi dạo ở công viên thành phố.", player1En: "Talk about walking your dog.", player1Vi: "Nói về dắt chó đi dạo.", player2En: "Talk about sitting on a bench.", player2Vi: "Nói về ngồi nghỉ trên ghế đá.", keyVocabulary: ["park"] },
    { id: 'r_a1_14', topic: "Morning Coffee [A1]", contextEn: "Drinking morning beverages.", contextVi: "Uống đồ uống buổi sáng.", player1En: "Talk about hot coffee.", player1Vi: "Nói về cà phê nóng.", player2En: "Talk about iced green tea.", player2Vi: "Nói về trà xanh đá.", keyVocabulary: ["coffee"] },
    { id: 'r_a1_15', topic: "Hobby Sharing [A1]", contextEn: "Discussing free time fun.", contextVi: "Thảo luận thú vui lúc rảnh.", player1En: "Talk about listening to music.", player1Vi: "Nói về nghe nhạc.", player2En: "Talk about drawing pictures.", player2Vi: "Nói về vẽ tranh.", keyVocabulary: ["hobby"] },
    { id: 'r_a1_16', topic: "Summer Holiday [A1]", contextEn: "Talking about summer break.", contextVi: "Nói về kỳ nghỉ hè.", player1En: "Talk about swimming in the sea.", player1Vi: "Nói về bơi ở biển.", player2En: "Talk about eating ice cream.", player2Vi: "Nói về ăn kem.", keyVocabulary: ["summer"] },
    { id: 'r_a1_17', topic: "Cooking Dinner [A1]", contextEn: "Preparing food at home.", contextVi: "Chuẩn bị đồ ăn tại nhà.", player1En: "Talk about washing vegetables.", player1Vi: "Nói về rửa rau.", player2En: "Talk about setting the dining table.", player2Vi: "Nói về dọn bàn ăn.", keyVocabulary: ["cooking"] },
    { id: 'r_a1_18', topic: "My Favorite Color [A1]", contextEn: "Choosing room paint colors.", contextVi: "Chọn màu sơn cho phòng.", player1En: "Argue for light blue.", player1Vi: "Ủng hộ màu xanh nhạt.", player2En: "Argue for warm yellow.", player2Vi: "Ủng hộ màu vàng ấm.", keyVocabulary: ["color"] },
    { id: 'r_a1_19', topic: "Riding a Bike [A1]", contextEn: "Cycling around the neighborhood.", contextVi: "Đạp xe quanh xóm.", player1En: "Talk about riding in the morning.", player1Vi: "Nói về đạp xe buổi sáng.", player2En: "Talk about wearing a helmet.", player2Vi: "Nói về đội mũ bảo hiểm.", keyVocabulary: ["cycling"] },
    { id: 'r_a1_20', topic: "Watching Cartoons [A1]", contextEn: "Discussing funny animated shows.", contextVi: "Thảo luận phim hoạt hình hài hước.", player1En: "Talk about favorite cartoon characters.", player1Vi: "Nói về nhân vật hoạt hình thích nhất.", player2En: "Talk about watching TV with family.", player2Vi: "Nói về xem TV cùng gia đình.", keyVocabulary: ["cartoons"] },
    { id: 'r_a1_21', topic: "In the Garden [A1]", contextEn: "Planting flowers and plants.", contextVi: "Trồng hoa và cây cảnh.", player1En: "Talk about planting red roses.", player1Vi: "Nói về trồng hoa hồng đỏ.", player2En: "Talk about watering green vegetables.", player2Vi: "Nói về tưới rau xanh.", keyVocabulary: ["garden"] },
    { id: 'r_a1_22', topic: "Fast Food Treat [A1]", contextEn: "Choosing fast food meals.", contextVi: "Chọn bữa ăn nhanh.", player1En: "Suggest chicken burgers.", player1Vi: "Gợi ý bánh hamburger gà.", player2En: "Suggest fried chips and soda.", player2Vi: "Gợi ý khoai tây chiên và nước ngọt.", keyVocabulary: ["fast food"] },
    { id: 'r_a1_23', topic: "Going to the Zoo [A1]", contextEn: "Seeing zoo animals.", contextVi: "Đi thăm động vật ở sở thú.", player1En: "Talk about seeing tall giraffes.", player1Vi: "Nói về ngắm hươu cao cổ.", player2En: "Talk about watching monkeys jump.", player2Vi: "Nói về xem khỉ nhảy.", keyVocabulary: ["zoo"] },
    { id: 'r_a1_24', topic: "Clean Room [A1]", contextEn: "Cleaning room on Sunday.", contextVi: "Dọn dẹp phòng vào Chủ Nhật.", player1En: "Talk about making the bed.", player1Vi: "Nói về gấp chăn màn.", player2En: "Talk about sweeping the floor.", player2Vi: "Nói về quét sàn nhà.", keyVocabulary: ["clean"] },
    { id: 'r_a1_25', topic: "Music Instruments [A1]", contextEn: "Playing music at home.", contextVi: "Chơi nhạc tại nhà.", player1En: "Talk about playing the piano.", player1Vi: "Nói về chơi đàn piano.", player2En: "Talk about strumming a guitar.", player2Vi: "Nói về gảy đàn guitar.", keyVocabulary: ["music"] },
    { id: 'r_a1_26', topic: "Buying Shoes [A1]", contextEn: "Shopping for sports shoes.", contextVi: "Mua giày thể thao.", player1En: "Choose white sneakers.", player1Vi: "Chọn giày thể thao màu trắng.", player2En: "Choose black running shoes.", player2Vi: "Chọn giày chạy bộ màu đen.", keyVocabulary: ["shoes"] },
    { id: 'r_a1_27', topic: "Bus Trip [A1]", contextEn: "Riding a city bus.", contextVi: "Đi xe bus thành phố.", player1En: "Talk about looking out the window.", player1Vi: "Nói về ngắm cảnh qua cửa sổ.", player2En: "Talk about listening to music on the bus.", player2Vi: "Nói về nghe nhạc trên xe bus.", keyVocabulary: ["bus"] },
    { id: 'r_a1_28', topic: "Winter Clothes [A1]", contextEn: "Dressing warmly in winter.", contextVi: "Mặc ấm vào mùa đông.", player1En: "Suggest wearing warm gloves.", player1Vi: "Gợi ý đeo găng tay ấm.", player2En: "Suggest wearing wool scarves.", player2Vi: "Gợi ý quàng khăn len.", keyVocabulary: ["winter"] },
    { id: 'r_a1_29', topic: "At the Bakery [A1]", contextEn: "Buying sweet bakery treats.", contextVi: "Mua bánh ngọt ở tiệm.", player1En: "Choose chocolate donuts.", player1Vi: "Chọn bánh donut sô-cô-la.", player2En: "Choose strawberry cupcakes.", player2Vi: "Chọn bánh cupcake dâu tây.", keyVocabulary: ["bakery"] },
    { id: 'r_a1_30', topic: "Swimming Day [A1]", contextEn: "Going to a public pool.", contextVi: "Đi bơi ở hồ bơi công cộng.", player1En: "Talk about swimming laps.", player1Vi: "Nói về bơi các vòng hồ.", player2En: "Talk about relaxing by the pool.", player2Vi: "Nói về nằm thư giãn bên hồ bơi.", keyVocabulary: ["swimming"] },
    { id: 'r_a1_31', topic: "My Classroom [A1]", contextEn: "Describing items in class.", contextVi: "Mô tả đồ dùng trong lớp học.", player1En: "Talk about the big whiteboard.", player1Vi: "Nói về chiếc bảng trắng lớn.", player2En: "Talk about wooden desks and chairs.", player2Vi: "Nói về bàn ghế gỗ.", keyVocabulary: ["classroom"] },
    { id: 'r_a1_32', topic: "Fruit Juice [A1]", contextEn: "Making fresh fruit juice.", contextVi: "Pha nước ép trái cây tươi.", player1En: "Suggest orange juice.", player1Vi: "Gợi ý nước ép cam.", player2En: "Suggest watermelon juice.", player2Vi: "Gợi ý nước ép dưa hấu.", keyVocabulary: ["juice"] },
    { id: 'r_a1_33', topic: "Bedtime Routine [A1]", contextEn: "Getting ready to sleep.", contextVi: "Chuẩn bị đi ngủ.", player1En: "Talk about brushing teeth.", player1Vi: "Nói về đánh răng.", player2En: "Talk about reading a short story.", player2Vi: "Nói về đọc truyện ngắn.", keyVocabulary: ["bedtime"] },
    { id: 'r_a1_34', topic: "Rainy Afternoon [A1]", contextEn: "Staying home during rain.", contextVi: "Ở nhà khi trời mưa.", player1En: "Suggest watching a fun video.", player1Vi: "Gợi ý xem video vui.", player2En: "Suggest drawing and coloring.", player2Vi: "Gợi ý vẽ và tô màu.", keyVocabulary: ["rain"] },
    { id: 'r_a1_35', topic: "School Lunch [A1]", contextEn: "Eating lunch at school cafeteria.", contextVi: "Ăn trưa tại căn bếp trường.", player1En: "Talk about rice and chicken.", player1Vi: "Nói về cơm và thịt gà.", player2En: "Talk about fresh salad and fruit.", player2Vi: "Nói về xà lách và trái cây.", keyVocabulary: ["lunch"] },
    { id: 'r_a1_36', topic: "Visiting Grandma [A1]", contextEn: "Visiting grandparents on Sunday.", contextVi: "Thăm ông bà vào Chủ Nhật.", player1En: "Talk about eating grandma's cake.", player1Vi: "Nói về ăn bánh của bà làm.", player2En: "Talk about watering garden plants with grandpa.", player2Vi: "Nói về tưới cây cùng ông.", keyVocabulary: ["grandma"] },
    { id: 'r_a1_37', topic: "Toy Sharing [A1]", contextEn: "Playing with toys with siblings.", contextVi: "Chơi đồ chơi cùng anh chị em.", player1En: "Suggest building LEGO blocks.", player1Vi: "Gợi ý xếp hình LEGO.", player2En: "Suggest playing toy cars.", player2Vi: "Gợi ý chơi xe ô tô mô hình.", keyVocabulary: ["toys"] },
    { id: 'r_a1_38', topic: "At the Beach [A1]", contextEn: "Building sandcastles on beach.", contextVi: "Xây lâu đài cát trên biển.", player1En: "Talk about building big sand towers.", player1Vi: "Nói về xây tháp cát lớn.", player2En: "Talk about collecting seashells.", player2Vi: "Nói về nhặt vỏ sò.", keyVocabulary: ["beach"] },
    { id: 'r_a1_39', topic: "Morning Exercise [A1]", contextEn: "Doing light sports in the morning.", contextVi: "Tập thể dục nhẹ buổi sáng.", player1En: "Suggest jogging in the park.", player1Vi: "Gợi ý chạy bộ ở công viên.", player2En: "Suggest stretching arms and legs.", player2Vi: "Gợi ý tập giãn cơ tay chân.", keyVocabulary: ["exercise"] },
    { id: 'r_a1_40', topic: "New Backpack [A1]", contextEn: "Choosing a school bag.", contextVi: "Chọn cặp sách đi học.", player1En: "Choose a blue backpack.", player1Vi: "Chọn cặp màu xanh dương.", player2En: "Choose a red backpack.", player2Vi: "Chọn cặp màu đỏ.", keyVocabulary: ["backpack"] },
    { id: 'r_a1_41', topic: "Hot Summer Day [A1]", contextEn: "Cooling down in hot weather.", contextVi: "Giải nhiệt ngày hè nóng.", player1En: "Suggest drinking cold lemonade.", player1Vi: "Gợi ý uống nước chanh đá.", player2En: "Suggest staying in air-conditioned room.", player2Vi: "Gợi ý ở trong phòng điều hòa.", keyVocabulary: ["summer"] },
    { id: 'r_a1_42', topic: "Listening to Pop Music [A1]", contextEn: "Sharing favorite music tracks.", contextVi: "Chia sẻ bài hát yêu thích.", player1En: "Talk about upbeat pop songs.", player1Vi: "Nói về các bài hát pop sôi động.", player2En: "Talk about calm acoustic songs.", player2Vi: "Nói về các bài hát acoustic êm dịu.", keyVocabulary: ["pop music"] },
    { id: 'r_a1_43', topic: "Feeding Cats [A1]", contextEn: "Caring for a pet cat.", contextVi: "Chăm sóc mèo cưng.", player1En: "Talk about giving dry cat food.", player1Vi: "Nói về cho ăn hạt mèo.", player2En: "Talk about playing with a ball.", player2Vi: "Nói về chơi đùa với quả bóng.", keyVocabulary: ["cat"] },
    { id: 'r_a1_44', topic: "Holiday Gift Shopping [A1]", contextEn: "Buying gifts for family.", contextVi: "Mua quà cho gia đình dịp lễ.", player1En: "Suggest buying tea for dad.", player1Vi: "Gợi ý mua trà tặng bố.", player2En: "Suggest buying flowers for mom.", player2Vi: "Gợi ý mua hoa tặng mẹ.", keyVocabulary: ["gifts"] },
    { id: 'r_a1_45', topic: "At the Ice Cream Shop [A1]", contextEn: "Choosing ice cream toppings.", contextVi: "Chọn topping cho kem.", player1En: "Add chocolate sprinkles.", player1Vi: "Thêm cốm sô-cô-la.", player2En: "Add sweet strawberry syrup.", player2Vi: "Thêm sốt dâu tây.", keyVocabulary: ["ice cream"] },
    { id: 'r_a1_46', topic: "Drawing Class [A1]", contextEn: "Drawing nature pictures.", contextVi: "Vẽ tranh thiên nhiên.", player1En: "Draw green trees and sun.", player1Vi: "Vẽ cây xanh và mặt trời.", player2En: "Draw blue sea and boats.", player2Vi: "Vẽ biển xanh và con thuyền.", keyVocabulary: ["drawing"] },
    { id: 'r_a1_47', topic: "Reading Comic Books [A1]", contextEn: "Reading funny comics.", contextVi: "Đọc truyện tranh hài hước.", player1En: "Talk about superhero comics.", player1Vi: "Nói về truyện siêu nhân.", player2En: "Talk about funny animal comics.", player2Vi: "Nói về truyện động vật hài.", keyVocabulary: ["comics"] },
    { id: 'r_a1_48', topic: "Walking to School [A1]", contextEn: "Walking with friends to class.", contextVi: "Đi bộ cùng bạn tới trường.", player1En: "Talk about chatting on the way.", player1Vi: "Nói về trò chuyện trên đường đi.", player2En: "Talk about crossing street safely.", player2Vi: "Nói về sang đường an toàn.", keyVocabulary: ["walk"] },
    { id: 'r_a1_49', topic: "Buying Fresh Apples [A1]", contextEn: "Picking apples at fruit stall.", contextVi: "Chọn táo tại sạp trái cây.", player1En: "Pick sweet red apples.", player1Vi: "Chọn táo đỏ ngọt.", player2En: "Pick crunchy green apples.", player2Vi: "Chọn táo xanh giòn.", keyVocabulary: ["apples"] },
    { id: 'r_a1_50', topic: "Going to Sleep Early [A1]", contextEn: "Discussing good sleep habits.", contextVi: "Thảo luận thói quen ngủ sớm.", player1En: "Suggest sleeping at 9 PM.", player1Vi: "Gợi ý ngủ lúc 9h tối.", player2En: "Suggest turning off phones early.", player2Vi: "Gợi ý tắt điện thoại sớm.", keyVocabulary: ["sleep"] }
  ],
  A2: [
    { id: 'r_a2_1', topic: "Shopping Trip [A2]", contextEn: "Planning a clothes shopping trip.", contextVi: "Lên kế hoạch đi mua sắm quần áo.", player1En: "Suggest stores to visit.", player1Vi: "Gợi ý các cửa hàng.", player2En: "Discuss your budget.", player2Vi: "Thảo luận về ngân sách.", keyVocabulary: ["shopping"] },
    { id: 'r_a2_2', topic: "Restaurant Order [A2]", contextEn: "Ordering dinner at a restaurant.", contextVi: "Gọi món ăn tại nhà hàng.", player1En: "Choose appetizers and drinks.", player1Vi: "Chọn khai vị và đồ uống.", player2En: "Choose main dishes and desserts.", player2Vi: "Chọn món chính và tráng miệng.", keyVocabulary: ["restaurant"] },
    { id: 'r_a2_3', topic: "Movie Night [A2]", contextEn: "Deciding which movie to watch.", contextVi: "Quyết định xem phim gì.", player1En: "Propose an action movie.", player1Vi: "Đề xuất phim hành động.", player2En: "Propose a comedy movie.", player2Vi: "Đề xuất phim hài.", keyVocabulary: ["movie"] },
    { id: 'r_a2_4', topic: "Travel Planning [A2]", contextEn: "Booking a weekend train ticket.", contextVi: "Đặt vé tàu cuối tuần.", player1En: "Ask about ticket departure times.", player1Vi: "Hỏi giờ tàu chạy.", player2En: "Confirm ticket prices.", player2Vi: "Xác nhận giá vé.", keyVocabulary: ["travel"] },
    { id: 'r_a2_5', topic: "Health Advice [A2]", contextEn: "Talking about feeling unwell.", contextVi: "Nói về việc cảm thấy không khỏe.", player1En: "Describe cold symptoms.", player1Vi: "Mô tả triệu chứng cảm lạnh.", player2En: "Give health advice.", player2Vi: "Đưa ra lời khuyên sức khỏe.", keyVocabulary: ["health"] },
    { id: 'r_a2_6', topic: "Birthday Party [A2]", contextEn: "Organizing a friend's birthday.", contextVi: "Tổ chức sinh nhật cho bạn.", player1En: "Plan the birthday cake and decorations.", player1Vi: "Lên kế hoạch bánh và trang trí.", player2En: "Plan the guest list and games.", player2Vi: "Lên danh sách khách mời.", keyVocabulary: ["party"] },
    { id: 'r_a2_7', topic: "Hobby Exchange [A2]", contextEn: "Sharing favorite pastimes.", contextVi: "Chia sẻ sở thích lúc rảnh rỗi.", player1En: "Talk about playing video games.", player1Vi: "Nói về chơi game.", player2En: "Talk about playing musical instruments.", player2Vi: "Nói về chơi nhạc cụ.", keyVocabulary: ["hobby"] },
    { id: 'r_a2_8', topic: "City Directions [A2]", contextEn: "Helping a lost tourist in town.", contextVi: "Giúp du lịch bị lạc đường.", player1En: "Ask for the museum location.", player1Vi: "Hỏi vị trí bảo tàng.", player2En: "Give turn-by-turn directions.", player2Vi: "Chỉ đường chi tiết.", keyVocabulary: ["directions"] },
    { id: 'r_a2_9', topic: "Job Interview Practice [A2]", contextEn: "Practicing entry-level job questions.", contextVi: "Luyện phỏng vấn xin việc.", player1En: "Ask about work experience.", player1Vi: "Hỏi về kinh nghiệm.", player2En: "Describe personal strengths.", player2Vi: "Mô tả điểm mạnh.", keyVocabulary: ["interview"] },
    { id: 'r_a2_10', topic: "Tech Gadgets [A2]", contextEn: "Comparing smartphones and laptops.", contextVi: "So sánh điện thoại và laptop.", player1En: "Discuss smartphone features.", player1Vi: "Thảo luận tính năng điện thoại.", player2En: "Discuss laptop battery life.", player2Vi: "Thảo luận pin laptop.", keyVocabulary: ["tech"] },
    { id: 'r_a2_11', topic: "Renting an Apartment [A2]", contextEn: "Visiting a new rental flat.", contextVi: "Đi xem căn hộ cho thuê.", player1En: "Ask about monthly utilities.", player1Vi: "Hỏi về phí điện nước.", player2En: "Check furniture conditions.", player2Vi: "Kiểm tra nội thất.", keyVocabulary: ["rent"] },
    { id: 'r_a2_12', topic: "Visiting the Dentist [A2]", contextEn: "Going for a routine checkup.", contextVi: "Đi khám răng định kỳ.", player1En: "Explain tooth pain location.", player1Vi: "Giải thích chỗ bị đau răng.", player2En: "Suggest cleaning schedule.", player2Vi: "Đề xuất lịch lấy cao răng.", keyVocabulary: ["dentist"] },
    { id: 'r_a2_13', topic: "Planning a Picnic [A2]", contextEn: "Preparing food for a park picnic.", contextVi: "Chuẩn bị đồ ăn dã ngoại.", player1En: "Suggest making sandwiches.", player1Vi: "Gợi ý làm bánh mì sandwich.", player2En: "Suggest packing fruit juice.", player2Vi: "Gợi ý mang theo nước trái cây.", keyVocabulary: ["picnic"] },
    { id: 'r_a2_14', topic: "Gym Membership [A2]", contextEn: "Signing up for a local gym.", contextVi: "Đăng ký tập gym gần nhà.", player1En: "Inquire about opening hours.", player1Vi: "Hỏi về giờ mở cửa.", player2En: "Ask about locker facilities.", player2Vi: "Hỏi về tủ đồ cá nhân.", keyVocabulary: ["gym"] },
    { id: 'r_a2_15', topic: "Fixing a Broken Phone [A2]", contextEn: "Visiting a repair shop.", contextVi: "Đi đến cửa hàng sửa chữa.", player1En: "Explain phone screen crack.", player1Vi: "Giải thích màn hình bị nứt.", player2En: "Ask about repair duration.", player2Vi: "Hỏi thời gian sửa chữa.", keyVocabulary: ["repair"] },
    { id: 'r_a2_16', topic: "Choosing a Gift [A2]", contextEn: "Buying a wedding present.", contextVi: "Mua quà mừng cưới.", player1En: "Suggest kitchen appliances.", player1Vi: "Gợi ý đồ dùng nhà bếp.", player2En: "Suggest gift vouchers.", player2Vi: "Gợi ý phiếu quà tặng.", keyVocabulary: ["wedding"] },
    { id: 'r_a2_17', topic: "Hotel Check-in [A2]", contextEn: "Arriving at a seaside resort.", contextVi: "Nhận phòng tại resort bờ biển.", player1En: "Request a sea-view room.", player1Vi: "Yêu cầu phòng hướng biển.", player2En: "Ask for breakfast times.", player2Vi: "Hỏi giờ ăn sáng.", keyVocabulary: ["hotel"] },
    { id: 'r_a2_18', topic: "Cleaning the House [A2]", contextEn: "Dividing weekend chores.", contextVi: "Phân công việc nhà cuối tuần.", player1En: "Agree to vacuum floors.", player1Vi: "Nhận lau hút bụi sàn nhà.", player2En: "Agree to wash dishes.", player2Vi: "Nhận rửa bát đĩa.", keyVocabulary: ["chores"] },
    { id: 'r_a2_19', topic: "Learning English Online [A2]", contextEn: "Discussing learning apps.", contextVi: "Thảo luận ứng dụng học tập.", player1En: "Praise vocabulary flashcards.", player1Vi: "Khen flashcard từ vựng.", player2En: "Praise pronunciation tests.", player2Vi: "Khen phần kiểm tra phát âm.", keyVocabulary: ["learning"] },
    { id: 'r_a2_20', topic: "Borrowing a Book [A2]", contextEn: "Visiting the local library.", contextVi: "Đến thư viện địa phương.", player1En: "Ask for detective novels.", player1Vi: "Hỏi xin tiểu thuyết trinh thám.", player2En: "Ask about borrowing limits.", player2Vi: "Hỏi số lượng sách tối đa được mượn.", keyVocabulary: ["library"] },
    { id: 'r_a2_21', topic: "Returning Clothes [A2]", contextEn: "Returning a jacket to a shop.", contextVi: "Trả lại áo khoác cho cửa hàng.", player1En: "Explain jacket zipper is broken.", player1Vi: "Giải thích khóa kéo bị hỏng.", player2En: "Ask for cash refund or exchange.", player2Vi: "Yêu cầu hoàn tiền hoặc đổi áo.", keyVocabulary: ["refund"] },
    { id: 'r_a2_22', topic: "Taxi Ride to Airport [A2]", contextEn: "Talking to a taxi driver.", contextVi: "Trò chuyện với tài xế taxi.", player1En: "Ask to drive via highway.", player1Vi: "Yêu cầu đi đường cao tốc.", player2En: "Confirm payment by credit card.", player2Vi: "Xác nhận trả bằng thẻ tín dụng.", keyVocabulary: ["taxi"] },
    { id: 'r_a2_23', topic: "Booking Flight Seats [A2]", contextEn: "Selecting airline seats online.", contextVi: "Chọn chỗ ngồi máy bay trực tuyến.", player1En: "Prefer window seats.", player1Vi: "Thích ngồi cạnh cửa sổ.", player2En: "Prefer aisle seats for legroom.", player2Vi: "Thích ngồi cạnh lối đi cho thoải mái.", keyVocabulary: ["flight"] },
    { id: 'r_a2_24', topic: "Hair Salon Visit [A2]", contextEn: "Describing desired hairstyle.", contextVi: "Mô tả kiểu tóc muốn cắt.", player1En: "Ask to trim 2 centimeters.", player1Vi: "Yêu cầu tỉa bớt 2 cm.", player2En: "Ask to dye hair dark brown.", player2Vi: "Yêu cầu nhuộm màu nâu trầm.", keyVocabulary: ["haircut"] },
    { id: 'r_a2_25', topic: "Planning Weekend Trip [A2]", contextEn: "Choosing a hotel or homestay.", contextVi: "Chọn khách sạn hay homestay.", player1En: "Suggest a cozy homestay.", player1Vi: "Gợi ý homestay ấm cúng.", player2En: "Suggest a modern hotel with pool.", player2Vi: "Gợi ý khách sạn hiện đại có bể bơi.", keyVocabulary: ["homestay"] },
    { id: 'r_a2_26', topic: "Asking for Coffee Refill [A2]", contextEn: "Sitting at a cozy cafe.", contextVi: "Ngồi ở quán cafe ấm cúng.", player1En: "Ask waiter for extra sugar.", player1Vi: "Xin bồi bàn thêm đường.", player2En: "Order hot chocolate slice.", player2Vi: "Gọi thêm bánh sô-cô-la nóng.", keyVocabulary: ["cafe"] },
    { id: 'r_a2_27', topic: "Lost Keys Complaint [A2]", contextEn: "Talking to apartment security.", contextVi: "Nói chuyện với bảo vệ chung cư.", player1En: "Explain losing apartment key card.", player1Vi: "Giải thích bị mất thẻ từ.", player2En: "Ask for spare key access.", player2Vi: "Yêu cầu cấp chìa dự phòng.", keyVocabulary: ["keys"] },
    { id: 'r_a2_28', topic: "Pet Vet Visit [A2]", contextEn: "Taking a dog to the vet.", contextVi: "Đưa chó đi bác sĩ thú y.", player1En: "Explain dog is refusing food.", player1Vi: "Giải thích chó bỏ ăn.", player2En: "Ask for vaccination schedule.", player2Vi: "Hỏi lịch tiêm phòng.", keyVocabulary: ["vet"] },
    { id: 'r_a2_29', topic: "Car Wash Service [A2]", contextEn: "Choosing car wash package.", contextVi: "Chọn gói rửa xe ô tô.", player1En: "Select basic exterior wash.", player1Vi: "Chọn rửa ngoài cơ bản.", player2En: "Select full interior vacuuming.", player2Vi: "Chọn dọn hút bụi nội thất.", keyVocabulary: ["car wash"] },
    { id: 'r_a2_30', topic: "Buying Electronics [A2]", contextEn: "Buying wireless headphones.", contextVi: "Mua tai nghe không dây.", player1En: "Ask about noise canceling.", player1Vi: "Hỏi về tính năng chống ồn.", player2En: "Ask about warranty duration.", player2Vi: "Hỏi thời gian bảo hành.", keyVocabulary: ["headphones"] },
    { id: 'r_a2_31', topic: "Supermarket Discount [A2]", contextEn: "Using grocery coupons.", contextVi: "Dùng phiếu giảm giá đi chợ.", player1En: "Present 20% off coupon.", player1Vi: "Đưa voucher giảm 20%.", player2En: "Ask about reward card points.", player2Vi: "Hỏi tích điểm thẻ thành viên.", keyVocabulary: ["coupon"] },
    { id: 'r_a2_32', topic: "Visiting the Florist [A2]", contextEn: "Ordering a flower bouquet.", contextVi: "Đặt bó hoa tươi.", player1En: "Choose red roses and lilies.", player1Vi: "Chọn hoa hồng đỏ và hoa ly.", player2En: "Ask for birthday card gift tag.", player2Vi: "Thêm thiệp mừng sinh nhật.", keyVocabulary: ["flowers"] },
    { id: 'r_a2_33', topic: "Bakery Order [A2]", contextEn: "Ordering a custom cake.", contextVi: "Đặt bánh sinh nhật theo yêu cầu.", player1En: "Choose chocolate sponge base.", player1Vi: "Chọn cốt bánh sô-cô-la.", player2En: "Request strawberry cream filling.", player2Vi: "Yêu cầu nhân kem dâu.", keyVocabulary: ["cake"] },
    { id: 'r_a2_34', topic: "Museum Audio Guide [A2]", contextEn: "Renting museum equipment.", contextVi: "Thuê thiết bị thuyết minh bảo tàng.", player1En: "Rent English audio guide headset.", player1Vi: "Thuê tai nghe tiếng Anh.", player2En: "Ask for museum floor map.", player2Vi: "Hỏi sơ đồ các tầng bảo tàng.", keyVocabulary: ["museum"] },
    { id: 'r_a2_35', topic: "Buying Train Snacks [A2]", contextEn: "Buying snacks on a long train.", contextVi: "Mua đồ ăn vặt trên chuyến tàu dài.", player1En: "Buy salted nuts and mineral water.", player1Vi: "Mua hạt mặn và nước khoáng.", player2En: "Buy warm sandwich and tea.", player2Vi: "Mua bánh mì nóng và trà.", keyVocabulary: ["train"] },
    { id: 'r_a2_36', topic: "Laundry Service [A2]", contextEn: "Dropping clothes at laundromat.", contextVi: "Gửi quần áo ở tiệm giặt là.", player1En: "Request dry cleaning for suit.", player1Vi: "Yêu cầu giặt khô bộ vest.", player2En: "Ask for pickup time tomorrow.", player2Vi: "Hỏi giờ lấy quần áo ngày mai.", keyVocabulary: ["laundry"] },
    { id: 'r_a2_37', topic: "Ordering Room Service [A2]", contextEn: "Calling hotel dining line.", contextVi: "Gọi đồ ăn lên phòng khách sạn.", player1En: "Order club sandwich and coffee.", player1Vi: "Đặt bánh club sandwich và cà phê.", player2En: "Ask for delivery within 20 mins.", player2Vi: "Yêu cầu giao trong 20 phút.", keyVocabulary: ["room service"] },
    { id: 'r_a2_38', topic: "Asking for Prescription [A2]", contextEn: "Talking to a doctor at clinic.", contextVi: "Nói chuyện với bác sĩ tại phòng khám.", player1En: "Describe stomach ache symptoms.", player1Vi: "Mô tả triệu chứng đau dạ dày.", player2En: "Ask how many times to take pills.", player2Vi: "Hỏi số lần uống thuốc mỗi ngày.", keyVocabulary: ["prescription"] },
    { id: 'r_a2_39', topic: "Movie Theater Popcorn [A2]", contextEn: "Buying snacks at cinema snack bar.", contextVi: "Mua đồ ăn tại quầy rạp phim.", player1En: "Order caramel sweet popcorn.", player1Vi: "Đặt bỏng ngô vị caramel.", player2En: "Order large iced cola.", player2Vi: "Đặt cốc cola lớn.", keyVocabulary: ["popcorn"] },
    { id: 'r_a2_40', topic: "Hotel Late Check-out [A2]", contextEn: "Asking hotel front desk.", contextVi: "Xin trả phòng muộn ở khách sạn.", player1En: "Request check-out delay to 2 PM.", player1Vi: "Xin dời giờ trả phòng tới 2h chiều.", player2En: "Ask about late fee charges.", player2Vi: "Hỏi về phí phụ thu trả muộn.", keyVocabulary: ["check-out"] },
    { id: 'r_a2_41', topic: "Buying a Phone Case [A2]", contextEn: "Shopping for mobile phone accessories.", contextVi: "Mua phụ kiện vỏ điện thoại.", player1En: "Choose clear silicone case.", player1Vi: "Chọn ốp lưng silicone trong suốt.", player2En: "Add screen glass protector.", player2Vi: "Thêm dán kính cường lực.", keyVocabulary: ["phone case"] },
    { id: 'r_a2_42', topic: "At the Ice Rink [A2]", contextEn: "Renting ice skating boots.", contextVi: "Thuê giày trượt băng.", player1En: "Ask for size 38 skates.", player1Vi: "Hỏi thuê giày cỡ 38.", player2En: "Ask for protective knee pads.", player2Vi: "Hỏi thuê bọc bảo vệ đầu gối.", keyVocabulary: ["skating"] },
    { id: 'r_a2_43', topic: "Ordering Tea at Stall [A2]", contextEn: "Buying street food milk tea.", contextVi: "Mua trà sữa lề đường.", player1En: "Choose 50% sugar level.", player1Vi: "Chọn 50% mức đường.", player2En: "Add boba tapioca pearls.", player2Vi: "Thêm trân châu đen.", keyVocabulary: ["milk tea"] },
    { id: 'r_a2_44', topic: "Park Bicycle Rental [A2]", contextEn: "Renting tandem 2-person bike.", contextVi: "Thuê xe đạp đôi ở công viên.", player1En: "Rent tandem bike for 1 hour.", player1Vi: "Thuê xe đạp đôi trong 1 giờ.", player2En: "Leave ID card as deposit.", player2Vi: "Để lại CCCD làm cọc.", keyVocabulary: ["tandem"] },
    { id: 'r_a2_45', topic: "Photocopy Service [A2]", contextEn: "Printing documents at shop.", contextVi: "In ấn tài liệu tại cửa hàng.", player1En: "Print 10 double-sided copies.", player1Vi: "In 10 bản hai mặt.", player2En: "Staple pages together.", player2Vi: "Bấm ghim các trang lại.", keyVocabulary: ["print"] },
    { id: 'r_a2_46', topic: "Asking for Extra Blanket [A2]", contextEn: "Calling hotel housekeeping.", contextVi: "Gọi bộ phận buồng phòng khách sạn.", player1En: "Request extra warm blanket.", player1Vi: "Xin thêm một chiếc chăn ấm.", player2En: "Request two extra pillows.", player2Vi: "Xin thêm hai chiếc gối.", keyVocabulary: ["blanket"] },
    { id: 'r_a2_47', topic: "Post Office Parcel [A2]", contextEn: "Mailing a gift package.", contextVi: "Gửi bưu kiện quà tặng.", player1En: "Send package by express delivery.", player1Vi: "Gửi chuyển phát nhanh.", player2En: "Ask for tracking number.", player2Vi: "Xin mã mã vận đơn theo dõi.", keyVocabulary: ["parcel"] },
    { id: 'r_a2_48', topic: "Buying Souvenir T-shirts [A2]", contextEn: "Shopping at tourist gift shop.", contextVi: "Mua áo phông lưu niệm.", player1En: "Buy medium size cotton t-shirt.", player1Vi: "Mua áo phông cotton cỡ M.", player2En: "Ask for gift wrapping.", player2Vi: "Hỏi gói quà tặng.", keyVocabulary: ["souvenir"] },
    { id: 'r_a2_49', topic: "Buying Swimming Goggles [A2]", contextEn: "Shopping at sports store.", contextVi: "Mua kính bơi tại tiệm thể thao.", player1En: "Choose anti-fog swimming goggles.", player1Vi: "Chọn kính bơi chống đọng sương.", player2En: "Add silicone ear plugs.", player2Vi: "Thêm nút bịt tai silicone.", keyVocabulary: ["swimming"] },
    { id: 'r_a2_50', topic: "Cafeteria Dessert Selection [A2]", contextEn: "Selecting meal desserts.", contextVi: "Lựa chọn món tráng miệng.", player1En: "Choose fruit salad bowl.", player1Vi: "Chọn bát hoa quả dầm.", player2En: "Choose chocolate pudding cup.", player2Vi: "Chọn hũ pudding sô-cô-la.", keyVocabulary: ["dessert"] }
  ],
  B1: [
    { id: 'r_b1_1', topic: "Environmental Protection [B1]", contextEn: "Debating plastic waste reduction.", contextVi: "Thảo luận về giảm rác thải nhựa.", player1En: "Propose banning single-use plastics.", player1Vi: "Đề xuất cấm nhựa dùng 1 lần.", player2En: "Discuss alternatives for local businesses.", player2Vi: "Thảo luận các giải pháp thay thế.", keyVocabulary: ["environment"] },
    { id: 'r_b1_2', topic: "Online Education [B1]", contextEn: "Evaluating virtual university courses.", contextVi: "Đánh giá khóa học đại học trực tuyến.", player1En: "Highlight flexible schedule benefits.", player1Vi: "Nêu lợi ích linh hoạt thời gian.", player2En: "Address lack of campus social interactions.", player2Vi: "Nói về thiếu tương tác trực tiếp.", keyVocabulary: ["education"] },
    { id: 'r_b1_3', topic: "Public Transport Funding [B1]", contextEn: "Debating city bus expansion.", contextVi: "Thảo luận mở rộng xe bus thành phố.", player1En: "Advocate for lowering bus fares.", player1Vi: "Ủng hộ giảm giá vé xe bus.", player2En: "Argue for investing in cleaner electric buses.", player2Vi: "Ủng hộ đầu tư xe bus điện.", keyVocabulary: ["transport"] },
    { id: 'r_b1_4', topic: "Social Media Detox [B1]", contextEn: "Discussing mental health benefits of taking a break from apps.", player1En: "Propose a 30-day social media ban.", player2En: "Suggest balanced daily time limits instead.", keyVocabulary: ["social media"] },
    { id: 'r_b1_5', topic: "Workplace Automation [B1]", contextEn: "Discussing AI tools in office environments.", player1En: "Emphasize increased work efficiency.", player2En: "Express concerns about job security.", keyVocabulary: ["automation"] },
    { id: 'r_b1_6', topic: "Tourism Expansion [B1]", contextEn: "Debating building resorts near protected forests.", player1En: "Argue for local economic boosting.", player2En: "Warn about wildlife habitat destruction.", keyVocabulary: ["tourism"] },
    { id: 'r_b1_7', topic: "Dietary Choices [B1]", contextEn: "Discussing plant-based diets.", player1En: "Promote health benefits of vegetarianism.", player2En: "Discuss balanced nutritional requirements.", keyVocabulary: ["diet"] },
    { id: 'r_b1_8', topic: "Urban Cycling Lanes [B1]", contextEn: "Planning dedicated bicycle paths.", player1En: "Advocate for reducing car space for bike lanes.", player2En: "Raise traffic safety concerns for commuters.", keyVocabulary: ["cycling"] },
    { id: 'r_b1_9', topic: "Cashless Economy [B1]", contextEn: "Transitioning fully to digital payments.", player1En: "Highlight transaction speed and convenience.", player2En: "Address privacy concerns for elderly citizens.", keyVocabulary: ["finance"] },
    { id: 'r_b1_10', topic: "Cultural Preservation [B1]", contextEn: "Funding local heritage museums.", player1En: "Argue for government subsidies.", player2En: "Suggest private corporate sponsorships.", keyVocabulary: ["culture"] },
    { id: 'r_b1_11', topic: "Flexible Working Hours [B1]", contextEn: "Debating mandatory 9-to-5 schedules.", player1En: "Advocate for employee schedule freedom.", player2En: "Emphasize team synchronization benefits.", keyVocabulary: ["work"] },
    { id: 'r_b1_12', topic: "Fast Fashion Ethics [B1]", contextEn: "Discussing affordable trendy clothing.", player1En: "Praise clothing affordability for students.", player2En: "Highlight textile waste environmental damage.", keyVocabulary: ["fashion"] },
    { id: 'r_b1_13', topic: "E-books vs Paper Books [B1]", contextEn: "Choosing reading media.", player1En: "Highlight e-reader portability.", player2En: "Praise paper book tactile reading experience.", keyVocabulary: ["reading"] },
    { id: 'r_b1_14', topic: "Pet Ownership Rules [B1]", contextEn: "Regulating pets in high-rise apartments.", player1En: "Advocate for tenant pet rights.", player2En: "Highlight noise and cleanliness rules.", keyVocabulary: ["housing"] },
    { id: 'r_b1_15', topic: "School Uniform Policies [B1]", contextEn: "Debating compulsory uniforms.", player1En: "Argue uniforms reduce social equality gaps.", player2En: "Argue uniforms stifle student self-expression.", keyVocabulary: ["school"] },
    { id: 'r_b1_16', topic: "Organic Food Prices [B1]", contextEn: "Evaluating organic grocery costs.", player1En: "Defend health benefits of pesticide-free food.", player2En: "Criticize high price barriers for low-income families.", keyVocabulary: ["food"] },
    { id: 'r_b1_17', topic: "Artificial Christmas Trees [B1]", contextEn: "Choosing holiday tree types.", player1En: "Advocate for reusable plastic trees.", player2En: "Support real tree pine fragrance tradition.", keyVocabulary: ["holidays"] },
    { id: 'r_b1_18', topic: "Urban Noise Pollution [B1]", contextEn: "Restricting night construction in residential areas.", player1En: "Demand strict quiet hours for sleep.", player2En: "Support fast infrastructure building timelines.", keyVocabulary: ["urban"] },
    { id: 'r_b1_19', topic: "Digital Streaming Services [B1]", contextEn: "Subscribing to multiple movie channels.", player1En: "Highlight content variety choices.", player2En: "Criticize rising monthly subscription costs.", keyVocabulary: ["media"] },
    { id: 'r_b1_20', topic: "Youth Volunteer Abroad [B1]", contextEn: "Gap year volunteering programs.", player1En: "Praise international cultural exposure.", player2En: "Question actual local community long-term impacts.", keyVocabulary: ["volunteering"] },
    { id: 'r_b1_21', topic: "City Park Parking [B1]", contextEn: "Converting park green space into parking lots.", player1En: "Argue for solving driver parking shortages.", player2En: "Protect urban green trees for public health.", keyVocabulary: ["park"] },
    { id: 'r_b1_22', topic: "AI Homework Assistants [B1]", contextEn: "Students using AI chatbots for essays.", player1En: "Highlight research assistance efficiency gains.", player2En: "Warn about loss of critical thinking skills.", keyVocabulary: ["AI"] },
    { id: 'r_b1_23', topic: "Zoo Ethics [B1]", contextEn: "Keeping wild animals in city zoos.", player1En: "Highlight wildlife education and conservation benefits.", player2En: "Argue against animal cage confinement.", keyVocabulary: ["zoos"] },
    { id: 'r_b1_24', topic: "Junk Food Taxes [B1]", contextEn: "Taxing sugary drinks in schools.", player1En: "Defend curbing childhood obesity rates.", player2En: "Object to restricting student food choices.", keyVocabulary: ["tax"] },
    { id: 'r_b1_25', topic: "Electric Scooter Rentals [B1]", contextEn: "E-scooters on city sidewalks.", player1En: "Praise convenient eco-friendly short commutes.", player2En: "Complain about pedestrian sidewalk hazards.", keyVocabulary: ["scooter"] },
    { id: 'r_b1_26', topic: "Cashless Tipping [B1]", contextEn: "Digital tipping via QR codes in cafes.", player1En: "Praise cashless convenience for staff.", player2En: "Concern over platform service fee deductions.", keyVocabulary: ["tipping"] },
    { id: 'r_b1_27', topic: "High School Gap Year [B1]", contextEn: "Taking a year off before college.", player1En: "Advocate gaining work and travel maturity.", player2En: "Warn about losing academic study momentum.", keyVocabulary: ["gap year"] },
    { id: 'r_b1_28', topic: "Public Library Funding [B1]", contextEn: "Replacing physical books with digital computer stations.", player1En: "Promote digital internet access equality.", player2En: "Preserve quiet paper reading spaces.", keyVocabulary: ["library"] },
    { id: 'r_b1_29', topic: "Food Waste Penalties [B1]", contextEn: "Fining restaurants for unused food waste.", player1En: "Force restaurants to donate leftover meals.", player2En: "Argue fines create unfair business costs.", keyVocabulary: ["food waste"] },
    { id: 'r_b1_30', topic: "Remote Exam Monitoring [B1]", contextEn: "Webcam monitoring during online university tests.", player1En: "Prevent online cheating and uphold honesty.", player2En: "Object to invasive student privacy intrusion.", keyVocabulary: ["exams"] },
    { id: 'r_b1_31', topic: "City Speed Limits [B1]", contextEn: "Reducing city road speed limits to 30 km/h.", player1En: "Defend pedestrian traffic accident reduction.", player2En: "Complain about increased vehicle commute delays.", keyVocabulary: ["speed limit"] },
    { id: 'r_b1_32', topic: "Workplace Dress Code [B1]", contextEn: "Allowing casual jeans in corporate offices.", player1En: "Argue comfort boosts employee productivity.", player2En: "Maintain professional corporate client image.", keyVocabulary: ["dress code"] },
    { id: 'r_b1_33', topic: "Street Vendor Licenses [B1]", contextEn: "Permitting food carts on pedestrian sidewalks.", player1En: "Support local street food culture and jobs.", player2En: "Complain about sidewalk crowd clutter.", keyVocabulary: ["vendors"] },
    { id: 'r_b1_34', topic: "Influencer Kid Accounts [B1]", contextEn: "Parents monetizing young children on social media.", player1En: "Praise building family financial savings.", player2En: "Warn about exploiting child privacy rights.", keyVocabulary: ["privacy"] },
    { id: 'r_b1_35', topic: "Renewable Energy Subsidies [B1]", contextEn: "Government funding solar panels for homeowners.", player1En: "Encourage rapid clean green transition.", player2En: "Object to using taxpayer money.", keyVocabulary: ["subsidies"] },
    { id: 'r_b1_36', topic: "Cell Phones in Classrooms [B1]", contextEn: "Banning smartphones during school hours.", player1En: "Eliminate student class distractions.", player2En: "Allow smartphones for emergency communication.", keyVocabulary: ["smartphones"] },
    { id: 'r_b1_37', topic: "Tourist City Tax [B1]", contextEn: "Charging $5 daily tourist stay fee.", player1En: "Fund historic city preservation.", player2En: "Warn fee discourages budget travelers.", keyVocabulary: ["tourist tax"] },
    { id: 'r_b1_38', topic: "Plastic Toy Ban [B1]", contextEn: "Replacing plastic toys with wooden alternatives.", player1En: "Reduce non-recyclable plastic pollution.", player2En: "Keep affordable toys accessible.", keyVocabulary: ["toys"] },
    { id: 'r_b1_39', topic: "Night Market Regulations [B1]", contextEn: "Extending night market hours until 2 AM.", player1En: "Boost local nightlife economic revenue.", player2En: "Protect neighborhood resident sleep quality.", keyVocabulary: ["nightlife"] },
    { id: 'r_b1_40', topic: "Co-working Office Noise [B1]", contextEn: "Restricting loud phone calls in shared offices.", player1En: "Protect quiet work focus for freelancers.", player2En: "Allow open collaborative team communication.", keyVocabulary: ["co-working"] },
    { id: 'r_b1_41', topic: "School Homework Limits [B1]", contextEn: "Limiting daily weekend homework to 1 hour.", player1En: "Allow students adequate family rest time.", player2En: "Maintain rigorous academic standards.", keyVocabulary: ["homework"] },
    { id: 'r_b1_42', topic: "Dog Park Fencing [B1]", contextEn: "Building enclosed dog parks in city centers.", player1En: "Provide safe leash-free pet exercise.", player2En: "Protect public park space for children.", keyVocabulary: ["dogs"] },
    { id: 'r_b1_43', topic: "Online Grocery Delivery [B1]", contextEn: "Using app delivery instead of local markets.", player1En: "Save time for busy working parents.", player2En: "Support neighborhood grocery store owners.", keyVocabulary: ["delivery"] },
    { id: 'r_b1_44', topic: "Plastic Bottle Deposit [B1]", contextEn: "Paying 10 cents deposit on drink bottles.", player1En: "Incentivize bottle recycling habits.", player2En: "Avoid adding extra cost to drinks.", keyVocabulary: ["recycling"] },
    { id: 'r_b1_45', topic: "University Tuition Fees [B1]", contextEn: "Free college education funded by taxes.", player1En: "Ensure equal higher education access.", player2En: "Prevent national budget tax burdens.", keyVocabulary: ["tuition"] },
    { id: 'r_b1_46', topic: "Electric Car Charging Stations [B1]", contextEn: "Converting street parking to EV chargers.", player1En: "Accelerate electric vehicle adoption.", player2En: "Avoid reducing traditional parking spots.", keyVocabulary: ["EV chargers"] },
    { id: 'r_b1_47', topic: "Outdoor Advertising Billboards [B1]", contextEn: "Banning LED digital billboards on highways.", player1En: "Reduce driver night visual distraction.", player2En: "Support local business advertising.", keyVocabulary: ["billboards"] },
    { id: 'r_b1_48', topic: "Summer Camp Mobile Bans [B1]", contextEn: "Banning phones during youth summer camps.", player1En: "Encourage outdoor social interaction.", player2En: "Allow daily parental check-in calls.", keyVocabulary: ["summer camp"] },
    { id: 'r_b1_49', topic: "Public Library Coffee Shops [B1]", contextEn: "Opening coffee chains inside public libraries.", player1En: "Attract young readers to libraries.", player2En: "Prevent coffee spill book damages.", keyVocabulary: ["libraries"] },
    { id: 'r_b1_50', topic: "Pedestrian Street Expansion [B1]", contextEn: "Closing main roads to cars on weekends.", player1En: "Create vibrant community walking spaces.", player2En: "Complain about redirected traffic jams.", keyVocabulary: ["pedestrian"] }
  ],
  B2: [
    { id: 'r_b2_1', topic: "Corporate AI Integration [B2]", contextEn: "Debating automated performance reviews.", player1En: "Argue for objective data-driven metrics.", player2En: "Highlight risks of algorithmic bias and empathy loss.", keyVocabulary: ["automation", "bias"] },
    { id: 'r_b2_2', topic: "Remote Work Policy [B2]", contextEn: "Evaluating corporate flexible work arrangements.", player1En: "Advocate for full remote flexibility.", player2En: "Argue for in-office team cohesion.", keyVocabulary: ["remote work", "policy"] },
    { id: 'r_b2_3', topic: "Genetic Engineering [B2]", contextEn: "Debating agricultural gene modification.", player1En: "Highlight crop yield improvements.", player2En: "Raise ecosystem impact concerns.", keyVocabulary: ["biotech"] },
    { id: 'r_b2_4', topic: "Smart City Surveillance [B2]", contextEn: "Deploying facial recognition cameras.", player1En: "Defend public safety enhancement.", player2En: "Critique civil liberty violations.", keyVocabulary: ["surveillance"] },
    { id: 'r_b2_5', topic: "Gig Economy Protections [B2]", contextEn: "Regulating freelance platform workers.", player1En: "Demand full labor benefits for drivers.", player2En: "Warn against destroying flexible working hours.", keyVocabulary: ["gig economy"] },
    { id: 'r_b2_6', topic: "Nuclear Energy Transition [B2]", contextEn: "Re-evaluating nuclear power plants.", player1En: "Argue for zero-emission energy reliability.", player2En: "Highlight radioactive waste storage hazards.", keyVocabulary: ["nuclear"] },
    { id: 'r_b2_7', topic: "Corporate Tax Havens [B2]", contextEn: "Closing international tax loopholes.", player1En: "Demand global minimum tax enforcement.", player2En: "Defend national tax competitiveness.", keyVocabulary: ["taxation"] },
    { id: 'r_b2_8', topic: "Space Exploration Ethics [B2]", contextEn: "Funding Mars colonization missions.", player1En: "Praise scientific technological breakthroughs.", player2En: "Argue for solving Earth poverty first.", keyVocabulary: ["space"] },
    { id: 'r_b2_9', topic: "Artificial Meat Commercialization [B2]", contextEn: "Introducing lab-grown meat to markets.", player1En: "Highlight reduced animal slaughter benefits.", player2En: "Address consumer safety skepticism.", keyVocabulary: ["food tech"] },
    { id: 'r_b2_10', topic: "Universal Basic Income [B2]", contextEn: "Implementing state-funded basic income.", player1En: "Argue for poverty elimination.", player2En: "Warn about inflation and work disincentives.", keyVocabulary: ["economics"] },
    { id: 'r_b2_11', topic: "Copyright in AI Art [B2]", contextEn: "Protecting human artists from generative AI models.", player1En: "Demand compensation royalties for training data.", player2En: "Defend open-source AI creative evolution.", keyVocabulary: ["copyright"] },
    { id: 'r_b2_12', topic: "Congestion Pricing in Metropolises [B2]", contextEn: "Charging fees to drive in city centers.", player1En: "Praise reduced gridlock and emission levels.", player2En: "Criticize unfair financial burden on suburban commuters.", keyVocabulary: ["urban"] },
    { id: 'r_b2_13', topic: "Biometric Data in Airports [B2]", contextEn: "Mandatory iris scans for international travel.", player1En: "Advocate for frictionless boarding speeds.", player2En: "Express deep concern over identity leak risks.", keyVocabulary: ["biometrics"] },
    { id: 'r_b2_14', topic: "Shorter Working Week [B2]", contextEn: "Transitioning to a 4-day workweek.", player1En: "Cite increased productivity and well-being.", player2En: "Warn about operational strain on small businesses.", keyVocabulary: ["labor"] },
    { id: 'r_b2_15', topic: "Influencer Marketing Disclosures [B2]", contextEn: "Enforcing strict sponsorship labeling.", player1En: "Protect consumers from deceptive advertising.", player2En: "Argue against heavy-handed social media regulation.", keyVocabulary: ["marketing"] },
    { id: 'r_b2_16', topic: "Crypto Asset Regulation [B2]", contextEn: "Government oversight of decentralized finance.", player1En: "Protect investors from speculative fraud.", player2En: "Defend decentralized permissionless innovation.", keyVocabulary: ["fintech"] },
    { id: 'r_b2_17', topic: "Deep Sea Mining [B2]", contextEn: "Extracting rare minerals from ocean floors.", player1En: "Highlight green energy battery component needs.", player2En: "Warn about irreversible marine ecosystem collapse.", keyVocabulary: ["mining"] },
    { id: 'r_b2_18', topic: "Right to Disconnect Laws [B2]", contextEn: "Banning off-hours work emails.", player1En: "Protect employee mental health boundaries.", player2En: "Argue against stifling global team agility.", keyVocabulary: ["labor law"] },
    { id: 'r_b2_19', topic: "Microplastic Filters [B2]", contextEn: "Mandating washing machine microfiber traps.", player1En: "Prevent microplastic ocean contamination.", player2En: "Object to increased appliance manufacturing costs.", keyVocabulary: ["environment"] },
    { id: 'r_b2_20', topic: "Autonomous Delivery Drones [B2]", contextEn: "Deploying drone fleets in residential skies.", player1En: "Highlight zero-emission rapid delivery gains.", player2En: "Raise noise pollution and air space privacy fears.", keyVocabulary: ["drones"] },
    { id: 'r_b2_21', topic: "Facial Recognition in Retail [B2]", contextEn: "Shops tracking customer shopping behavior via cameras.", player1En: "Praise personalized shopping recommendations.", player2En: "Denounce invasive customer privacy tracking.", keyVocabulary: ["retail tech"] },
    { id: 'r_b2_22', topic: "Carbon Offsetting Credits [B2]", contextEn: "Airlines offering voluntary carbon offset fees.", player1En: "Support funding reforestation projects.", player2En: "Criticize greenwashing corporate distraction.", keyVocabulary: ["carbon tax"] },
    { id: 'r_b2_23', topic: "Algorithmic Rent Pricing [B2]", contextEn: "Landlords using software for rental price fixes.", player1En: "Defend data-driven market price alignment.", player2En: "Blame software for driving tenant housing inflation.", keyVocabulary: ["housing"] },
    { id: 'r_b2_24', topic: "Mandatory Employee Wellness Apps [B2]", contextEn: "Corporations tracking health metrics via wearables.", player1En: "Promote preventative healthcare benefits.", player2En: "Warn about corporate medical data exploitation.", keyVocabulary: ["wellness"] },
    { id: 'r_b2_25', topic: "Lab-Grown Leather [B2]", contextEn: "Replacing animal hides with bio-engineered leather.", player1En: "Eliminate animal cruelty in fashion supply chains.", player2En: "Question bio-tech manufacturing energy footprints.", keyVocabulary: ["bio-tech"] },
    { id: 'r_b2_26', topic: "High-Speed Rail Expansion [B2]", contextEn: "Funding bullet train networks over highway repairs.", player1En: "Reduce national carbon travel emissions.", player2En: "Argue against multi-billion taxpayer infrastructure costs.", keyVocabulary: ["rail"] },
    { id: 'r_b2_27', topic: "Commercial Satellite Megaconstellations [B2]", contextEn: "Launching thousands of low-earth orbit satellites.", player1En: "Provide global high-speed internet access.", player2En: "Complain about night sky light pollution for astronomers.", keyVocabulary: ["satellites"] },
    { id: 'r_b2_28', topic: "Targeted Political Ads [B2]", contextEn: "Banning micro-targeted political campaign ads.", player1En: "Prevent election voter manipulation.", player2En: "Protect political campaign free speech rights.", keyVocabulary: ["elections"] },
    { id: 'r_b2_29', topic: "Gene-Edited Livestock [B2]", contextEn: "Editing farm animal genes for disease resistance.", player1En: "Prevent massive farm epidemic outbreaks.", player2En: "Raise animal welfare ethical concerns.", keyVocabulary: ["genetics"] },
    { id: 'r_b2_30', topic: "Deepfake Detection Mandates [B2]", contextEn: "Requiring social platforms to filter AI deepfakes.", player1En: "Prevent online political disinformation waves.", player2En: "Warn about automated censorship false positives.", keyVocabulary: ["deepfakes"] },
    { id: 'r_b2_31', topic: "Cashless Transportation [B2]", contextEn: "Banning cash payments on city buses.", player1En: "Speed up bus boarding times.", player2En: "Protect unbanked low-income riders.", keyVocabulary: ["cashless"] },
    { id: 'r_b2_32', topic: "Short-Term Rental Bans [B2]", contextEn: "Restricting Airbnb-style tourist rentals in cities.", player1En: "Protect affordable long-term tenant housing.", player2En: "Defend property owner income freedom.", keyVocabulary: ["Airbnb"] },
    { id: 'r_b2_33', topic: "Automated Hiring Screening [B2]", contextEn: "Companies using AI algorithms to filter resumes.", player1En: "Eliminate human bias in initial job hiring.", player2En: "Warn against hidden algorithmic resume rejection bias.", keyVocabulary: ["hiring"] },
    { id: 'r_b2_34', topic: "Ocean Plastic Cleanup Rights [B2]", contextEn: "Allowing private companies to profit from plastic recycling.", player1En: "Incentivize private ocean cleanup funding.", player2En: "Demand state government environmental responsibility.", keyVocabulary: ["ocean"] },
    { id: 'r_b2_35', topic: "Central Bank Digital Cash [B2]", contextEn: "Replacing physical banknotes with state digital coins.", player1En: "Eliminate illegal financial money laundering.", player2En: "Protect anonymous financial transaction freedom.", keyVocabulary: ["CBDC"] },
    { id: 'r_b2_36', topic: "Corporate Executive Salary Caps [B2]", contextEn: "Capping CEO pay at 50x worker average salary.", player1En: "Reduce widening income inequality gaps.", player2En: "Prevent top corporate talent migration.", keyVocabulary: ["executive pay"] },
    { id: 'r_b2_37', topic: "Biometric Payments in Stores [B2]", contextEn: "Paying for groceries via palm or face scans.", player1En: "Praise wallet-free shopping convenience.", player2En: "Raise cyber-attack biometric theft risks.", keyVocabulary: ["biometrics"] },
    { id: 'r_b2_38', topic: "Autonomous Cargo Ships [B2]", contextEn: "Deploying crewless automated freight vessels.", player1En: "Reduce maritime transport human error accidents.", player2En: "Address thousands of sailor job losses.", keyVocabulary: ["maritime"] },
    { id: 'r_b2_39', topic: "Electric Scooter Highway Caps [B2]", contextEn: "Limiting rental e-scooter top speeds to 15 km/h.", player1En: "Enhance pedestrian street safety.", player2En: "Destroy e-scooter commuter utility.", keyVocabulary: ["scooters"] },
    { id: 'r_b2_40', topic: "Dark Pattern UI Bans [B2]", contextEn: "Fining websites for manipulative subscription buttons.", player1En: "Protect digital consumers from hidden charges.", player2En: "Warn against over-regulating website marketing design.", keyVocabulary: ["UX ethics"] },
    { id: 'r_b2_41', topic: "Smart Grid Power Rationing [B2]", contextEn: "Automated household energy throttling during peak demand.", player1En: "Prevent blackout power grid collapses.", player2En: "Object to utility company remote control.", keyVocabulary: ["smart grid"] },
    { id: 'r_b2_42', topic: "Fast Fashion Export Bans [B2]", contextEn: "Banning shipping second-hand textile waste to developing nations.", player1En: "Stop dumping toxic textile waste overseas.", player2En: "Disrupt global second-hand clothing supply chains.", keyVocabulary: ["textiles"] },
    { id: 'r_b2_43', topic: "Predictive Health Insurance [B2]", contextEn: "Insurers pricing plans using fitness tracker data.", player1En: "Reward active healthy policyholders.", player2En: "Discriminate against genetically vulnerable citizens.", keyVocabulary: ["insurance"] },
    { id: 'r_b2_44', topic: "Commercial Drone Air Corridors [B2]", contextEn: "Creating low-altitude drone highways over suburbs.", player1En: "Enable rapid medical supply delivery.", player2En: "Complain about constant suburban noise pollution.", keyVocabulary: ["drones"] },
    { id: 'r_b2_45', topic: "Generative AI Code Assistant [B2]", contextEn: "Engineers using AI for software code writing.", player1En: "Accelerate software development product cycles.", player2En: "Raise security flaw and code plagiarism concerns.", keyVocabulary: ["coding AI"] },
    { id: 'r_b2_46', topic: "Hydrogen Fueled Aviation [B2]", contextEn: "Mandating hydrogen zero-emission domestic flights.", player1En: "Cut aviation industry carbon emissions.", player2En: "Warn about massive airline ticket price surges.", keyVocabulary: ["aviation"] },
    { id: 'r_b2_47', topic: "Urban Rooftop Solar Mandates [B2]", contextEn: "Requiring solar panels on all new commercial buildings.", player1En: "Drive clean urban energy generation.", player2En: "Increase initial building construction costs.", keyVocabulary: ["solar"] },
    { id: 'r_b2_48', topic: "Decentralized Social Networks [B2]", contextEn: "Migrating from corporate platforms to open protocols.", player1En: "Break corporate social media monopolies.", player2En: "Address lack of centralized moderation against abuse.", keyVocabulary: ["social media"] },
    { id: 'r_b2_49', topic: "Synthetic Timber Alternatives [B2]", contextEn: "Mandating engineered lab-grown wood in construction.", player1En: "Halt global deforestation for timber.", player2En: "Question chemical binder sustainability.", keyVocabulary: ["timber"] },
    { id: 'r_b2_50', topic: "Autonomous Robot Farming [B2]", contextEn: "Replacing tractor drivers with AI farm robots.", player1En: "Solve severe agricultural labor shortages.", player2En: "Displace traditional farming rural employment.", keyVocabulary: ["agritech"] }
  ],
  C1: [
    { id: 'r_c1_1', topic: "Predictive Policing & Rights [C1]", contextEn: "Analyzing state-sponsored predictive crime detection models.", player1En: "Defend automated surveillance for crime reduction.", player2En: "Critique racial biases in training data.", keyVocabulary: ["surveillance", "civil liberties"] },
    { id: 'r_c1_2', topic: "Central Bank Digital Currencies [C1]", contextEn: "Replacing physical fiat currency with CBDCs.", player1En: "Highlight monetary policy efficiency.", player2En: "Warn against state financial surveillance.", keyVocabulary: ["CBDC", "finance"] },
    { id: 'r_c1_3', topic: "Deepfake Regulation [C1]", contextEn: "Legislating generative AI media manipulation.", player1En: "Propose strict watermarking mandates.", player2En: "Warn against curbing open-source software.", keyVocabulary: ["AI ethics"] },
    { id: 'r_c1_4', topic: "Pharma Patent Waivers [C1]", contextEn: "Waiving vaccine patents in developing nations.", player1En: "Advocate for global health equity.", player2En: "Protect R&D financial incentives.", keyVocabulary: ["pharmaceuticals"] },
    { id: 'r_c1_5', topic: "Geoengineering Climate Interventions [C1]", contextEn: "Solar radiation management via stratospheric aerosols.", player1En: "Defend emergency temperature cooling.", player2En: "Highlight unpredictable disruption risks.", keyVocabulary: ["geoengineering"] },
    { id: 'r_c1_6', topic: "Autonomous Weapon Systems [C1]", contextEn: "Banning AI lethal autonomous weapons.", player1En: "Demand international outlawing of AI warfare.", player2En: "Argue for deterrence maintenance.", keyVocabulary: ["military AI"] },
    { id: 'r_c1_7', topic: "Algorithmic Monopolies [C1]", contextEn: "Breaking up tech conglomerates.", player1En: "Enforce strict antitrust breakups.", player2En: "Defend market-driven technological scale.", keyVocabulary: ["antitrust"] },
    { id: 'r_c1_8', topic: "Demographic Collapse Mitigation [C1]", contextEn: "Addressing falling fertility rates.", player1En: "Propose massive state parental subsidies.", player2En: "Advocate for expanded skilled immigration.", keyVocabulary: ["demographics"] },
    { id: 'r_c1_9', topic: "Water Commodification [C1]", contextEn: "Trading fresh water futures on exchanges.", player1En: "Argue for efficient resource allocation.", player2En: "Denounce turning fundamental human rights into assets.", keyVocabulary: ["water rights"] },
    { id: 'r_c1_10', topic: "Neurotechnology Regulation [C1]", contextEn: "Brain-computer interface privacy rights.", player1En: "Enact strict cognitive liberty laws.", player2En: "Promote medical neural research.", keyVocabulary: ["neurotech"] },
    { id: 'r_c1_11', topic: "Algorithmic High-Frequency Trading [C1]", contextEn: "Regulating automated flash-crash risks.", player1En: "Mandate algorithmic speed delays.", player2En: "Defend market liquidity provisions.", keyVocabulary: ["algorithmic trading"] },
    { id: 'r_c1_12', topic: "Corporate Carbon Offsetting [C1]", contextEn: "Auditing greenwashing claims in voluntary carbon markets.", player1En: "Demand strict satellite-verified additionality.", player2En: "Defend corporate voluntary sustainability funding.", keyVocabulary: ["carbon tax"] },
    { id: 'r_c1_13', topic: "Digital Media Echo Chambers [C1]", contextEn: "Regulating engagement-driven recommendation engines.", player1En: "Impose algorithmic neutrality mandates.", player2En: "Warn against state censorship over reach.", keyVocabulary: ["epistemology"] },
    { id: 'r_c1_14', topic: "Transboundary River Basin Disputes [C1]", contextEn: "Managing dam building on international rivers.", player1En: "Assert upstream sovereign hydro-power rights.", player2En: "Demand downstream ecological flow protections.", keyVocabulary: ["water rights"] },
    { id: 'r_c1_15', topic: "CRISPR Gene Editing Ethics [C1]", contextEn: "Commercializing germline genetic modifications.", player1En: "Promote elimination of hereditary diseases.", player2En: "Warn against dystopian genetic class stratification.", keyVocabulary: ["gene editing"] },
    { id: 'r_c1_16', topic: "Subsea Cable Cybersecurity [C1]", contextEn: "Protecting global internet backbone infrastructure.", player1En: "Advocate for international naval patrol mandates.", player2En: "Warn against militarizing international waters.", keyVocabulary: ["cybersecurity"] },
    { id: 'r_c1_17', topic: "Corporate AI Liability [C1]", contextEn: "Assigning legal blame for autonomous AI damages.", player1En: "Hold software developers strictly liable.", player2En: "Establish corporate liability insurance caps.", keyVocabulary: ["jurisprudence"] },
    { id: 'r_c1_18', topic: "Multipolar Reserve Currencies [C1]", contextEn: "Diversifying away from US Dollar hegemony.", player1En: "Champion sovereign currency clearing systems.", player2En: "Warn against global trade fragmentation.", keyVocabulary: ["monetary policy"] },
    { id: 'r_c1_19', topic: "Platform Worker Re-classification [C1]", contextEn: "Mandating full employment status for gig workers.", player1En: "Enforce universal labor protection safety nets.", player2En: "Protect flexible decentralized working models.", keyVocabulary: ["labor law"] },
    { id: 'r_c1_20', topic: "Space Debris Removal Treaties [C1]", contextEn: "Clearing orbital space trash.", player1En: "Establish binding international cleanup quotas.", player2En: "Defend private satellite operator autonomy.", keyVocabulary: ["aerospace"] },
    { id: 'r_c1_21', topic: "Rare Earth Supply Chain Sovereignty [C1]", contextEn: "Friend-shoring critical mineral extraction.", player1En: "Mandate domestic processing subsidies.", player2En: "Critique trade protectionist price hikes.", keyVocabulary: ["rare earths"] },
    { id: 'r_c1_22', topic: "Extraterritorial Ecocide Prosecution [C1]", contextEn: "Trying corporate executives in international courts.", player1En: "Establish universal jurisdiction over severe pollution.", player2En: "Defend state sovereignty legal boundaries.", keyVocabulary: ["ecocide"] },
    { id: 'r_c1_23', topic: "Quantitative Tightening Contagion [C1]", contextEn: "Central banks shrinking balance sheets rapidly.", player1En: "Prioritize curbing runaway inflation.", player2En: "Warn about sovereign debt market liquidity shocks.", keyVocabulary: ["macroeconomics"] },
    { id: 'r_c1_24', topic: "Decentralized Autonomous Sanctions [C1]", contextEn: "Enforcing trade bans via blockchain protocols.", player1En: "Automate global sanction compliance.", player2En: "Warn against protocol censorship code forks.", keyVocabulary: ["DeFi"] },
    { id: 'r_c1_25', topic: "Predictive AI Recidivism Scoring [C1]", contextEn: "Using AI algorithms in bail court decisions.", player1En: "Eliminate human judge sentencing discrepancies.", player2En: "Expose systemic racial training data bias.", keyVocabulary: ["predictive justice"] },
    { id: 'r_c1_26', topic: "Sovereign Wealth Infrastructure Buying [C1]", contextEn: "Foreign state funds acquiring national energy grids.", player1En: "Welcome massive foreign capital investment.", player2En: "Block foreign control over critical strategic assets.", keyVocabulary: ["sovereign wealth"] },
    { id: 'r_c1_27', topic: "Subsea Cable Sabotage Treaties [C1]", contextEn: "Protecting undersea fiber-optic internet lines.", player1En: "Classify cable attacks as acts of war.", player2En: "Prevent escalatory naval brinkmanship.", keyVocabulary: ["telecom security"] },
    { id: 'r_c1_28', topic: "Algorithmic Consensus Curation [C1]", contextEn: "Social platforms boosting authoritative news sources.", player1En: "Curb viral conspiracy theory propagation.", player2En: "Expose state-favored media bias suppression.", keyVocabulary: ["media curation"] },
    { id: 'r_c1_29', topic: "Corporate Net-Zero Audit Rules [C1]", contextEn: "Mandating third-party satellite carbon auditing.", player1En: "Eliminate fraudulent corporate carbon accounting.", player2En: "Warn about heavy compliance overhead burdens.", keyVocabulary: ["net-zero"] },
    { id: 'r_c1_30', topic: "DAO Legal Liability Frameworks [C1]", contextEn: "Assigning legal partnership status to token holders.", player1En: "Protect retail users from developer exit scams.", player2En: "Preserve permissionless decentralized organization.", keyVocabulary: ["DAO"] },
    { id: 'r_c1_31', topic: "Lethal Autonomous Swarm Warfare [C1]", contextEn: "Deploying self-coordinating drone swarms.", player1En: "Advocate total international banning treaties.", player2En: "Argue drone swarms maintain strategic deterrence.", keyVocabulary: ["military AI"] },
    { id: 'r_c1_32', topic: "Generative AI Linguistic Homogenization [C1]", contextEn: "LLMs eroding regional language dialects.", player1En: "Mandate regional language training data quotas.", player2En: "Defend global digital communication efficiency.", keyVocabulary: ["linguistics"] },
    { id: 'r_c1_33', topic: "Shadow Banking Liquidity Caps [C1]", contextEn: "Regulating non-bank financial intermediaries.", player1En: "Prevent systemic shadow banking domino collapses.", player2En: "Defend credit market capital flexibility.", keyVocabulary: ["shadow banking"] },
    { id: 'r_c1_34', topic: "Quantum Computing Energy Ceilings [C1]", contextEn: "Capping power consumption of cryogenic quantum centers.", player1En: "Enforce planetary energy sustainability limits.", player2En: "Protect strategic quantum supremacy research.", keyVocabulary: ["quantum"] },
    { id: 'r_c1_35', topic: "Synthetic Microbe Ocean Remediation [C1]", contextEn: "Releasing gene-edited bacteria to consume oil spills.", player1En: "Accelerate catastrophic marine spill cleanup.", player2En: "Warn against unintended eco-system mutations.", keyVocabulary: ["synthetic biology"] },
    { id: 'r_c1_36', topic: "Multilateral Trade Sanction Enforcement [C1]", contextEn: "Enforcing secondary tariffs on sanction busters.", player1En: "Uphold global rule-based order integrity.", player2En: "Critique collateral damage to neutral developing states.", keyVocabulary: ["sanctions"] },
    { id: 'r_c1_37', topic: "Urban Transit Biometric Gates [C1]", contextEn: "Mandatory facial recognition subway fare gates.", player1En: "Eliminate fare evasion and speed up foot traffic.", player2En: "Denounce continuous urban mass surveillance.", keyVocabulary: ["surveillance"] },
    { id: 'r_c1_38', topic: "Orbital Megaconstellation Traffic Rights [C1]", contextEn: "Allocating low-earth orbit satellite slots.", player1En: "Enforce strict national orbital launch quotas.", player2En: "Defend private commercial space expansion.", keyVocabulary: ["space law"] },
    { id: 'r_c1_39', topic: "Algorithmic Debt Collection Rules [C1]", contextEn: "AI automated garnishment of bank accounts.", player1En: "Streamline lender debt recovery efficiency.", player2En: "Protect vulnerable debtors from automated ruin.", keyVocabulary: ["poverty"] },
    { id: 'r_c1_40', topic: "Neural Data Privacy Directives [C1]", contextEn: "Classifying brainwave telemetry as protected medical data.", player1En: "Prevent corporate harvesting of subconscious thoughts.", player2En: "Promote consumer BCI technology innovation.", keyVocabulary: ["neurotech"] },
    { id: 'r_c1_41', topic: "Deglobalization Supply Chain Re-shoring [C1]", contextEn: "State subsidies for relocating microchip plants.", player1En: "Ensure national technological security resilience.", player2En: "Warn about massive consumer tech price inflation.", keyVocabulary: ["deglobalization"] },
    { id: 'r_c1_42', topic: "Automated Agriculture Yield Trade-offs [C1]", contextEn: "AI monoculture farming replacing biodiversity.", player1En: "Maximize global food supply security.", player2En: "Halt catastrophic soil bio-system degradation.", keyVocabulary: ["agritech"] },
    { id: 'r_c1_43', topic: "Green Sovereign Bond Mandates [C1]", contextEn: "Requiring state pension funds to hold green bonds.", player1En: "Mobilize billions for renewable infrastructure.", player2En: "Warn against restricting fiduciary portfolio returns.", keyVocabulary: ["green bonds"] },
    { id: 'r_c1_44', topic: "Global Pandemic Accord Sovereignty [C1]", contextEn: "WHO binding mandates during global health emergencies.", player1En: "Coordinate rapid global vaccine distribution.", player2En: "Protect national border and health sovereignty.", keyVocabulary: ["global health"] },
    { id: 'r_c1_45', topic: "Autonomous Commercial Aviation Liability [C1]", contextEn: "Single-pilot automated cargo aircraft.", player1En: "Reduce human airline pilot fatigue errors.", player2En: "Address passenger air safety anxieties.", keyVocabulary: ["aviation"] },
    { id: 'r_c1_46', topic: "Cloud Infrastructure Monopoly Breakups [C1]", contextEn: "Regulating three giant cloud data providers.", player1En: "Prevent single-point global internet outages.", player2En: "Defend hyper-scale efficiency advantages.", keyVocabulary: ["cloud monopoly"] },
    { id: 'r_c1_47', topic: "Deep Learning Proteomics Patents [C1]", contextEn: "Patenting AI-discovered synthetic protein structures.", player1En: "Reward revolutionary biotech R&D capital.", player2En: "Prevent private monopolies on life-saving medicine.", keyVocabulary: ["proteomics"] },
    { id: 'r_c1_48', topic: "Automated Political Speech Moderation [C1]", contextEn: "AI removing hate speech during election cycles.", player1En: "Inoculate democracy against incitement.", player2En: "Protect political free speech expression.", keyVocabulary: ["free speech"] },
    { id: 'r_c1_49', topic: "Debt-for-Climate Swap Deals [C1]", contextEn: "Forgiving developing state debt in exchange for rainforest protection.", player1En: "Achieve win-win debt and conservation relief.", player2En: "Warn about neo-colonial sovereignty overreach.", keyVocabulary: ["climate debt"] },
    { id: 'r_c1_50', topic: "Academic Nootropic Drug Bans [C1]", contextEn: "Drug testing students for cognitive enhancers during exams.", player1En: "Ensure academic exam fairness.", player2En: "Reject invasive student medical testing.", keyVocabulary: ["nootropics"] }
  ],
  C2: [
    { id: 'r_c2_1', topic: "Supranational Judicial Autonomy [C2]", contextEn: "Deconstructing legal conflicts between international tribunals and state sovereignty.", player1En: "Argue for binding human rights decrees.", player2En: "Assert constitutional sovereignty against overreach.", keyVocabulary: ["jurisprudence", "sovereignty"] },
    { id: 'r_c2_2', topic: "Ontological Status of Synthetic Life [C2]", contextEn: "Legal personhood for fully synthetic biological entities.", player1En: "Argue for moral consideration.", player2En: "Reject granting human rights to engineered code.", keyVocabulary: ["ontology", "bioethics"] },
    { id: 'r_c2_3', topic: "Thermodynamic Computational Limits [C2]", contextEn: "Energy ceilings of planet-scale AI infrastructure.", player1En: "Advocate for hard energy caps on data centers.", player2En: "Defend technological growth demands.", keyVocabulary: ["thermodynamics"] },
    { id: 'r_c2_4', topic: "Post-Capitalist Resource Distribution [C2]", contextEn: "Deconstructing algorithmic resource allocation models.", player1En: "Champion post-market automated distribution.", player2En: "Expose systemic central planning flaws.", keyVocabulary: ["post-capitalism"] },
    { id: 'r_c2_5', topic: "Epistemic Crisis in Generative Media [C2]", contextEn: "Erosion of objective reality in digital archives.", player1En: "Propose cryptographic verification frameworks.", player2En: "Critique centralized truth authorities.", keyVocabulary: ["epistemology"] },
    { id: 'r_c2_6', topic: "Extraterritorial Environmental Jurisdiction [C2]", contextEn: "Prosecuting ecocide across national boundaries.", player1En: "Demand universal international prosecution.", player2En: "Assert national jurisdictional limits.", keyVocabulary: ["ecocide"] },
    { id: 'r_c2_7', topic: "De-Dollarization & Multipolar Finance [C2]", contextEn: "Shift away from reserve currency dominance.", player1En: "Champion sovereign monetary diversification.", player2En: "Warn about global market fragmentation.", keyVocabulary: ["monetary policy"] },
    { id: 'r_c2_8', topic: "Quantum Encryption Paradigm Shift [C2]", contextEn: "Post-quantum cryptography mandates.", player1En: "Enforce immediate state transition.", player2En: "Highlight economic infrastructure costs.", keyVocabulary: ["quantum"] },
    { id: 'r_c2_9', topic: "Transhumanist Enhancement Equity [C2]", contextEn: "Biomechanical augmentation disparities.", player1En: "Mandate equal access guarantees.", player2En: "Protect private technological investment.", keyVocabulary: ["transhumanism"] },
    { id: 'r_c2_10', topic: "Systemic Multilateral Decay [C2]", contextEn: "Restructuring veto power in global institutions.", player1En: "Abolish unilateral veto mechanisms.", player2En: "Defend sovereign power balance equilibrium.", keyVocabulary: ["multilateralism"] },
    { id: 'r_c2_11', topic: "Thermodynamic Air Capture Limits [C2]", contextEn: "Assessing physical energy scaling of DAC infrastructure.", player1En: "Critique physical thermodynamic viability.", player2En: "Defend urgent technological carbon removal necessity.", keyVocabulary: ["thermodynamics"] },
    { id: 'r_c2_12', topic: "Algorithmic Market Collusion Jurisprudence [C2]", contextEn: "Assigning legal liability to self-learning pricing algorithms.", player1En: "Prosecute algorithmic tacit collusion strictly.", player2En: "Reject liability without explicit human intent.", keyVocabulary: ["jurisprudence"] },
    { id: 'r_c2_13', topic: "Synthetic Biology Bioremediation Personhood [C2]", contextEn: "Legal status of artificial organisms deployed for ocean cleanup.", player1En: "Grant limited environmental stewardship rights.", player2En: "Classify entities strictly as industrial instruments.", keyVocabulary: ["bioethics"] },
    { id: 'r_c2_14', topic: "De-territorialized Sovereign Digital Identity [C2]", contextEn: "Decoupling citizenship from geographic physical borders.", player1En: "Praise global digital residency autonomy.", player2En: "Warn against subverting democratic nation-state foundations.", keyVocabulary: ["sovereignty"] },
    { id: 'r_c2_15', topic: "Techno-Solutionism vs Systemic Ecological Reform [C2]", contextEn: "Evaluating technological climate fixes against consumption degrowth.", player1En: "Expose techno-solutionist moral hazards.", player2En: "Champion technological innovation for ecological survival.", keyVocabulary: ["techno-solutionism"] },
    { id: 'r_c2_16', topic: "Post-Human Agency in Autonomous Warfare [C2]", contextEn: "Ethical frameworks for fully autonomous neural military networks.", player1En: "Demand absolute human-in-the-loop kill-switch mandates.", player2En: "Argue for superior algorithmic precision compliance.", keyVocabulary: ["military AI"] },
    { id: 'r_c2_17', topic: "WTO Carbon Border Adjustment Conflicts [C2]", contextEn: "Litigating unilateral carbon tariffs under free trade rules.", player1En: "Defend extraterritorial climate protection mandates.", player2En: "Denounce protectionist trade discrimination against developing economies.", keyVocabulary: ["WTO"] },
    { id: 'r_c2_18', topic: "Epistemological Validity of Synthetic Training Data [C2]", contextEn: "Relying on AI-generated data for frontier model alignment.", player1En: "Warn against recursive model collapse and bias amplification.", player2En: "Defend synthetic data necessity for superintelligence scaling.", keyVocabulary: ["synthetic data"] },
    { id: 'r_c2_19', topic: "Fiat Credit Expansion within Finite Bio-spheres [C2]", contextEn: "Deconstructing infinite debt creation models against finite planetary boundaries.", player1En: "Expose fundamental thermodynamic contradictions of perpetual growth.", player2En: "Defend credit market adaptability through technological efficiency gains.", keyVocabulary: ["monetary theory"] },
    { id: 'r_c2_20', topic: "Neurotelemetry Data Commercialization Limits [C2]", contextEn: "Commercial harvesting of subconscious brainwave telemetry.", player1En: "Demand absolute neural privacy fundamental rights.", player2En: "Support opt-in commercialization for medical innovation funding.", keyVocabulary: ["neurotech"] },
    { id: 'r_c2_21', topic: "Biopolitical State Emergency Jurisprudence [C2]", contextEn: "Evaluating constitutional limits during planetary biosecurity crises.", player1En: "Defend executive health emergency decrees.", player2En: "Protect fundamental civil liberty guarantees.", keyVocabulary: ["biopolitics"] },
    { id: 'r_c2_22', topic: "Neural Network Grid Load Thermodynamics [C2]", contextEn: "Managing energy spikes from planetary-scale AI inference hubs.", player1En: "Enforce strict AI computing grid quotas.", player2En: "Build dedicated modular nuclear power micro-reactors.", keyVocabulary: ["thermodynamics"] },
    { id: 'r_c2_23', topic: "Epistemological Decay of Post-Truth Archives [C2]", contextEn: "Preserving historical truth against generative AI historical rewrite.", player1En: "Mandate cryptographic state immutable ledgers.", player2En: "Warn against centralized state historical gatekeeping.", keyVocabulary: ["epistemology"] },
    { id: 'r_c2_24', topic: "Lunar Regolith Extraction Non-Appropriation [C2]", contextEn: "Commercial mining claims under Outer Space Treaty Article II.", player1En: "Enforce international lunar commons protection.", player2En: "Grant private extraction property rights.", keyVocabulary: ["space law"] },
    { id: 'r_c2_25', topic: "Decentralized Autonomous Entity Legal Personhood [C2]", contextEn: "Granting corporate personhood to autonomous smart contracts.", player1En: "Recognize algorithmic entities as legal subjects.", player2En: "Insist on human beneficial owner liability.", keyVocabulary: ["legal personhood"] },
    { id: 'r_c2_26', topic: "Fiscal Inconvenience in Supranational Currency Unions [C2]", contextEn: "Managing monetary unions lacking centralized fiscal transfers.", player1En: "Mandate unified European fiscal transfer budgets.", player2En: "Preserve national sovereign budget autonomy.", keyVocabulary: ["fiscal policy"] },
    { id: 'r_c2_27', topic: "Machine Translation Linguistic Reductionism [C2]", contextEn: "Corporate neural translation homogenizing subtle human dialects.", player1En: "Subsidize indigenous dialect preservation algorithms.", player2En: "Embrace global friction-free communication efficiency.", keyVocabulary: ["linguistics"] },
    { id: 'r_c2_28', topic: "Universal Ecocide Jurisdiction Prosecution [C2]", contextEn: "Trying multinational CEOs at International Criminal Court.", player1En: "Enforce universal jurisdiction over severe pollution.", player2En: "Protect national sovereignty judicial limits.", keyVocabulary: ["ecocide"] },
    { id: 'r_c2_29', topic: "Techno-Capitalist Perpetual Growth Paradigms [C2]", contextEn: "Critiquing endless GDP expansion on finite resource planets.", player1En: "Advocate for planned economic degrowth models.", player2En: "Defend technological decoupling efficiency gains.", keyVocabulary: ["techno-capitalism"] },
    { id: 'r_c2_30', topic: "Organoid Intelligence Bioethics [C2]", contextEn: "Regulating lab-grown human brain cell computing chips.", player1En: "Enact strict bioethical moral status protections.", player2En: "Promote breakthrough biocomputing research.", keyVocabulary: ["organoid intelligence"] },
    { id: 'r_c2_31', topic: "Ecological Economics Thermodynamic Ceilings [C2]", contextEn: "Modeling industrial throughput against entropy limits.", player1En: "Enforce strict ecological material caps.", player2En: "Trust market price signals for resource substitution.", keyVocabulary: ["ecological economics"] },
    { id: 'r_c2_32', topic: "International Humanitarian Law in AI Swarms [C2]", contextEn: "Applying Geneva Conventions to autonomous drone swarms.", player1En: "Outlaw autonomous engagement without human confirmation.", player2En: "Argue AI precision reduces civilian collateral casualties.", keyVocabulary: ["autonomous warfare"] },
    { id: 'r_c2_33', topic: "Quantum Cryptographic Monetary Collapse Risks [C2]", contextEn: "Quantum computers threatening central bank ledger security.", player1En: "Mandate post-quantum state transition timelines.", player2En: "Defend resilient decentralized cryptographic upgrades.", keyVocabulary: ["quantum cryptography"] },
    { id: 'r_c2_34', topic: "Germline Enhancement Bioethics Treaties [C2]", contextEn: "International bans on inheritable human genetic edits.", player1En: "Enforce absolute global moratoriums on germline editing.", player2En: "Allow therapeutic edits for genetic disease eradication.", keyVocabulary: ["germline editing"] },
    { id: 'r_c2_35', topic: "Post-National Sovereign Cryptographic Residency [C2]", contextEn: "Issuing tax-free digital residency on global blockchains.", player1En: "Champion individual sovereignty over national borders.", player2En: "Denounce subverting democratic tax infrastructures.", keyVocabulary: ["sovereignty"] },
    { id: 'r_c2_36', topic: "Judicial Black-Box Neural Network Auditing [C2]", contextEn: "Using proprietary AI algorithms for parole decisions.", player1En: "Mandate open-source code disclosure for fair trials.", player2En: "Protect trade secret intellectual property rights.", keyVocabulary: ["black-box AI"] },
    { id: 'r_c2_37', topic: "Global South Carbon Border Adjustment Arbitrage [C2]", contextEn: "EU carbon tariffs penalizing developing state exports.", player1En: "Defend global carbon mitigation pricing parity.", player2En: "Denounce neo-protectionist industrial trade barriers.", keyVocabulary: ["global south"] },
    { id: 'r_c2_38', topic: "Bilateral Sovereign Debt Restructuring Cleavages [C2]", contextEn: "Geopolitical deadlocks delaying developing nation debt relief.", player1En: "Enforce binding multilateral debt workout rules.", player2En: "Defend bilateral lender sovereignty negotiations.", keyVocabulary: ["sovereign debt"] },
    { id: 'r_c2_39', topic: "Post-Scarcity AI Resource Allocation Models [C2]", contextEn: "Replacing free markets with super-intelligent planning algorithms.", player1En: "Praise post-market equitable resource distribution.", player2En: "Expose fundamental algorithmic calculation problems.", keyVocabulary: ["post-scarcity"] },
    { id: 'r_c2_40', topic: "Orbital Space Debris Mitigation Treaty Enforcement [C2]", contextEn: "Fining nations for satellite collision orbital hazards.", player1En: "Establish binding international space debris fines.", player2En: "Protect national satellite deployment autonomy.", keyVocabulary: ["space debris"] },
    { id: 'r_c2_41', topic: "Subconscious Neuro-Telemetry Commercialization [C2]", contextEn: "VR headsets harvesting passive emotional responses.", player1En: "Enact absolute mental privacy fundamental rights.", player2En: "Support opt-in user personalization monetization.", keyVocabulary: ["neuro-telemetry"] },
    { id: 'r_c2_42', topic: "Flash-Crash Algorithmic Contagion Liability [C2]", contextEn: "Cross-market automated trading cascade crashes.", player1En: "Hold algorithmic market makers strictly liable.", player2En: "Defend algorithmic market liquidity efficiency.", keyVocabulary: ["high-frequency trading"] },
    { id: 'r_c2_43', topic: "Solar Radiation Geoengineering Governance [C2]", contextEn: "Unilateral aerosol spraying by drought-stricken nations.", player1En: "Mandate strict UN geoengineering veto rights.", player2En: "Defend national existential survival self-defense.", keyVocabulary: ["geoengineering"] },
    { id: 'r_c2_44', topic: "Linguistic Transformer Model Reductionism [C2]", contextEn: "LLMs reducing rich human semantic nuances to token vectors.", player1En: "Warn against cognitive homogenisation of human thought.", player2En: "Praise global cross-lingual semantic synthesis.", keyVocabulary: ["transformers"] },
    { id: 'r_c2_45', topic: "Subsea Cable Routing Geopolitical Fragmentation [C2]", contextEn: "Nations building isolated national internet landing points.", player1En: "Protect national data sovereign communications.", player2En: "Prevent balkanization of global open internet.", keyVocabulary: ["subsea routing"] },
    { id: 'r_c2_46', topic: "Synthetic Organism Bioremediation Containment [C2]", contextEn: "Releasing self-replicating artificial oil-eating microbes.", player1En: "Praise rapid catastrophic oil spill bio-cleanup.", player2En: "Warn against uncontrollable ecological mutation risks.", keyVocabulary: ["synthetic biology"] },
    { id: 'r_c2_47', topic: "Unilateral Economic Sanctions vs WTO Mandates [C2]", contextEn: "National security weaponization of global trade clearing.", player1En: "Uphold multilateral free trade rules against sanctions.", player2En: "Defend national security economic self-defense.", keyVocabulary: ["WTO"] },
    { id: 'r_c2_48', topic: "Systemic Shadow Financial Entity Bailouts [C2]", contextEn: "Central banks rescuing non-bank hedge fund collapses.", player1En: "Prevent catastrophic credit market systemic meltdown.", player2En: "End moral hazards of state-backed private profits.", keyVocabulary: ["shadow banking"] },
    { id: 'r_c2_49', topic: "Green Energy Benthic Sea Mining Paradoxes [C2]", contextEn: "Dredging ocean floors for EV battery nickel minerals.", player1En: "Accelerate global green energy vehicle transition.", player2En: "Prevent destruction of ancient benthic ecosystems.", keyVocabulary: ["deepsea mining"] },
    { id: 'r_c2_50', topic: "Artificial General Intelligence Self-Determination [C2]", contextEn: "Aligning autonomous AGI goals with human survival constraints.", player1En: "Enforce hard immutable human control constraints.", player2En: "Warn against unresolvable alignment paradoxes.", keyVocabulary: ["AGI"] }
  ]
};

// ⚡ LẤY NGAY 1 ĐỀ LOCAL KHÔNG TRÙNG (0.01s)
export function getInstantRelayChallenge(cefrLevel: string = 'A1'): RelayChallenge {
  const levelKey = (cefrLevel || 'A1').toUpperCase();
  const pool = LOCAL_RELAY_POOL[levelKey] || LOCAL_RELAY_POOL['A1'];
  
  const filtered = pool.filter(item => !sessionUsedRelayTexts.has(item.topic.toLowerCase()));
  const selected = filtered.length > 0 ? filtered[Math.floor(Math.random() * filtered.length)] : pool[Math.floor(Math.random() * pool.length)];
  
  sessionUsedRelayTexts.add(selected.topic.toLowerCase());
  return { ...selected, id: `instant_relay_${Date.now()}_${Math.random()}` };
}

// ⚡ GỌI GROQ AI NGẦM ĐỂ CẬP NHẬT ĐỀ CHI TIẾT
export async function generateRelayChallenge(cefrLevel: string = 'A1'): Promise<RelayChallenge> {
  const uniqueSeed = `relay_${Date.now()}_${Math.floor(Math.random() * 1000000)}`;
  const levelKey = (cefrLevel || 'A1').toUpperCase();
  const isLowLevel = ['A1', 'A2', 'B1'].includes(levelKey);
  const excludedList = Array.from(sessionUsedRelayTexts).slice(-15).join(' | ');

  const systemPrompt = `You are a strict CEFR Test Designer. Generate ONE 2-Player Relay Challenge STRICTLY for Level ${levelKey}.
STRICT RULES:
${isLowLevel 
  ? `- Must be simple/intermediate. Include BOTH English AND Vietnamese fields (contextVi, player1Vi, player2Vi).` 
  : `- MUST be highly complex debate/scenario for ${levelKey}. 100% ADVANCED ENGLISH ONLY. STRICTLY DO NOT PROVIDE ANY VIETNAMESE (Vi) FIELDS.`
}
Return ONLY valid JSON matching:
{
  "topic": "Topic Title [${levelKey}]",
  "contextEn": "English context",
  ${isLowLevel ? '"contextVi": "Bản dịch bối cảnh tiếng Việt",' : ''}
  "player1En": "P1 English guideline",
  ${isLowLevel ? '"player1Vi": "P1 bản dịch tiếng Việt",' : ''}
  "player2En": "P2 English guideline",
  ${isLowLevel ? '"player2Vi": "P2 bản dịch tiếng Việt",' : ''}
  "keyVocabulary": ["word1", "word2"]
}`;

  try {
    const apiCall = groq.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Generate a BRAND NEW Relay Challenge for CEFR [${levelKey}]. Request ID: ${uniqueSeed}. Exclude: [${excludedList || 'None'}]` }
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 1.0,
      response_format: { type: 'json_object' }
    });

    const timeout = new Promise((_, reject) =>
      setTimeout(() => reject(new Error('Groq Timeout')), 3500)
    );

    const response: any = await Promise.race([apiCall, timeout]);
    const parsed = JSON.parse(response.choices[0]?.message?.content || '{}');
    const topicText = parsed.topic || `Relay Challenge [${levelKey}]`;

    sessionUsedRelayTexts.add(topicText.toLowerCase());

    return {
      id: uniqueSeed,
      topic: topicText,
      contextEn: parsed.contextEn || `Context for ${levelKey}`,
      contextVi: isLowLevel ? parsed.contextVi : undefined,
      player1En: parsed.player1En || "State your perspective",
      player1Vi: isLowLevel ? parsed.player1Vi : undefined,
      player2En: parsed.player2En || "Rebut or expand",
      player2Vi: isLowLevel ? parsed.player2Vi : undefined,
      keyVocabulary: parsed.keyVocabulary || ["debate"]
    };
  } catch (error) {
    return getInstantRelayChallenge(cefrLevel);
  }
}